### ISSUE TITLE
Error handling on invalid value

### ISSUE THREAD

**Issue by KelvinKaYiuLok** [FirelyTeam/spark#101]
POST a patient resource with birthDate set to 1 (invalid value) causing exception, but it still allows the Patient document to be stored in the resources collection, updated the counters but no searchindex produced.

The error occurred when trying to map/convert value 1 to Hl7.Fhir.Model.Date

It would be nice if exception occurred, skips all database process such as store Patient document and update counter.

This also happened to PUT and I believe this could happen to the Transaction end point also.

**Comment by cknaap** [comment]
Thank you for reporting this. We probably won't fix this soon, but we will allow the behaviour you describe on a new incarnation of Spark that is currently under development. 
Could you elaborate on what you use Spark for?

**Comment by KelvinKaYiuLok** [comment]
I am currently doing research on different open source FHIR server software to find a suitable one to use for our project. The goal is to allow third party to exchange data with us using FHIR.

**Comment by cknaap** [comment]
Thank you for researching Spark then. As said, we're creating a new version from the ground up, built on ASP.NET Core, that is much more versatile. Are you interested in that?

**Comment by KelvinKaYiuLok** [comment]
Hi,

I am insterested

Kelvin

Kelvin Lok
Developer

[Stalis_signatureOrangelight]
Stalis Ltd

The Spendlove Centre, Charlbury, Oxford OX7 3PQ

Tel: 01608 810015 / Fax: 01608 819351 / www.stalis.com<blocked::http://www.stalis.com/>
Registered in England and Wales at the above address: 2585206

To receive our Company Newsletter please click here http://stalis.us8.list<http://stalis.us8.list-manage1.com/subscribe?u=0d461497b1b30d2a2357fda9e&id=78459bc27a>


[WOBA_2016_WINNER_Small Business Award Logo_sRGB_Winner]  [email-gps]

[ZA102637858]<https://twitter.com/StalisLtd>[ZA102637857]<https://www.linkedin.com/company/stalis-ltd>[http://www.starwoodhotels.com/Media/Graphics/Common/logos/SocialMedia/youtube_footer.png]<https://www.youtube.com/channel/UCxrJf96G_5c2MkygYpEWm6g>

**Comment by TPucke** [comment]
I'm curious to know whether the new implementation will incorporate any sort of authorization, such as (perhaps optional) validation of OAuth2 access token.  Any insights on the reasoning for or against would be appreciated as well.  Thanks.

**Comment by cknaap** [comment]
We're building the new implementation on top of ASP.NET Core. There are several [standard components ](https://docs.asp.net/en/latest/fundamentals/middleware.html#built-in-middleware)for *authentication* that you can put in the middleware pipeline, for example OAuth2. That is not directly tied to the FHIR Server functionality that Spark provides. How you map credentials to the access to specific (types of) resources is the domain of *authorization*, and is highly dependent on the setting in which Spark (or any server app) is used. [Security labels](http://www.hl7.org/implement/standards/fhir/security-labels.html#2.12.1) will be available in Spark, for the access control decision engine to use. On the short term we don't intend to write a 'standard' access control decision engine upfront. Maybe after a few real-life implementations, a pattern for this will emerge.

**Comment by cknaap** [comment]
@Kelvin: I'll contact you personally.

**Comment by KelvinKaYiuLok** [comment]
I think is a good starting point to include OAuth2 access token for authentication. The England FHIR community meeting that I have went to a couple of time, they have mentioned OAuth2 will be used as the authentication layer.

Kelvin

Kelvin Lok
Developer

[Stalis_signatureOrangelight]
Stalis Ltd

The Spendlove Centre, Charlbury, Oxford OX7 3PQ

Tel: 01608 810015 / Fax: 01608 819351 / www.stalis.com<blocked::http://www.stalis.com/>
Registered in England and Wales at the above address: 2585206

To receive our Company Newsletter please click here http://stalis.us8.list<http://stalis.us8.list-manage1.com/subscribe?u=0d461497b1b30d2a2357fda9e&id=78459bc27a>


[WOBA_2016_WINNER_Small Business Award Logo_sRGB_Winner]  [email-gps]

[ZA102637858]<https://twitter.com/StalisLtd>[ZA102637857]<https://www.linkedin.com/company/stalis-ltd>[http://www.starwoodhotels.com/Media/Graphics/Common/logos/SocialMedia/youtube_footer.png]<https://www.youtube.com/channel/UCxrJf96G_5c2MkygYpEWm6g>

**Comment by kennethmyhra** [comment]
Closing this since the later versions of https://github.com/firelyTeam/fhir-net-api have stricter parsing. Spark now returns a descriptive OperationOutcome for this type of error
