### ISSUE TITLE
search using _profile parameter no results

### ISSUE THREAD

**Issue by adkendall** [FirelyTeam/spark#104]
No results are returned when I search using _profile e.g. API/fhir/Observation?_profile=https://www.testfhirserver.net/FhirProfile/ActivityLog  - even though there are Observations with profile set correctly in meta data.

Is there an issue or am I doing something wrong?

**Comment by mbaltus** [comment]
You're not doing it wrong, it is an issue. Thank you for reporting!

**Comment by mbaltus** [comment]
To team: _profile is indexed as a string, but Spark builds the query with _profile as a code value.

**Comment by adkendall** [comment]
Thanks for the hint - simply changing searchParamType in FhirModel.LoadGenericSearchParameters() has solved it.
