### ISSUE TITLE
How to use custom profile? 

### ISSUE THREAD

**Issue by leo9223** [FirelyTeam/spark#111]
If I deploy spark on my machine then how I can use custom profiles with it?

**Comment by cknaap** [comment]
If you mean custom Structure Definitions: Spark is agnostic to them. It has no filter that can validate incoming resources against a SD. But maybe you meant something else by 'use custom profiles'?

**Comment by zoechi** [comment]
I'm also looking for a server that supports custom profiles like @cknaap describes.

**Comment by leo9223** [comment]
Yea I mean custom Structure Definition for a profile let's say for Patient. I want to deploy spark on my machine but I want to use custom Structure Definition for my patient profile. can I do that ?
