### ISSUE TITLE
Getting error from Post

### ISSUE THREAD

**Issue by HowardEdidin** [FirelyTeam/spark#112]
`<OperationOutcome xmlns="http://hl7.org/fhir">
    <issue>
        <severity value="error" />
        <diagnostics value="NotSupportedException: Operation not supported" />
    </issue>
    <issue>
        <severity value="information" />
        <diagnostics value="   at Spark.Engine.Service.FhirService.GetFeature[T]()&#xD;&#xA;   at Spark.Engine.Service.FhirService.Store(Entry entry)&#xD;&#xA;   at Spark.Engine.Service.FhirService.Create(IKey key, Resource resource)&#xD;&#xA;   at Spark.Controllers.FhirController.Create(String type, Resource resource)&#xD;&#xA;   at lambda_method(Closure , Object , Object[] )&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;&gt;c__DisplayClass10.&lt;GetExecutor&gt;b__9(Object instance, Object[] methodParameters)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" />
    </issue>
</OperationOutcome>`

**Comment by brianpos** [comment]
A little more context for the issue would help, like which server instance/version it is calling (apart from just spark) and what the request was.

**Comment by HowardEdidin** [comment]
Hi Brian,

I am using Postman to call the spark-dstu2-develop (Hl7.Fhir.DSTU2.0.91.1).

I was doing a GET on existing resources in my DocDB Repository.

[cid:image005.png@01D29B66.13DC9B80]

Thanks,


Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by mbaltus** [comment]
It seems like the server thinks you're trying to perform something else than just a normal read, and it complains about an operation that isn't supported. Can you give us the exact syntax you used for the GET?

**Comment by HowardEdidin** [comment]
You can access the API directly.

http://hl7fhirserver.azurewebsites.net/Home/Overview

Click on ProcessRequest which shows one resource.
If you click on any resource, nothing is returned in the browser.

I pasted the link into Postman and am now receiving the following error.

<OperationOutcome xmlns="http://hl7.org/fhir">
    <issue>
        <severity value="error" />
        <diagnostics value="NullReferenceException: Object reference not set to an instance of an object." />
    </issue>
    <issue>
        <severity value="information" />
        <diagnostics value="   at Spark.Controllers.FhirController.Search(String type)&#xD;&#xA;   at lambda_method(Closure , Object , Object[] )&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;&gt;c__DisplayClass10.&lt;GetExecutor&gt;b__9(Object instance, Object[] methodParameters)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" />
    </issue>
</OperationOutcome>

I had to remove the following from the FhirController because I got an exception returned in Postman about “cannot have a Constructor in an API Controller.

[InjectionConstructor]
        public FhirController(IFhirService fhirService)
        {
            // This will be a (injected) constructor parameter in ASP.vNext.
            _fhirService = fhirService;
        }


Thanks,


Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by mbaltus** [comment]
Okay, well... if you remove the initialization of _fhirService, _fhirService will be null. Naturally the controller is going to throw a null reference exception when the _fhirService is accessed subsequently.

I'm thinking your previous problem could be resulting from the same issue as I've answered in the [.Net Api Google group](https://groups.google.com/forum/#!topic/fhir-dotnet/hmFeCBBHok8). So perhaps you can revert to an older version of Spark and check if your interface works correctly then?

**Comment by HowardEdidin** [comment]
I am going to revert to the Master version.

I fixed a lot of the code issues. I optimized the code for performance.  I can share my changes with you.





Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP
Microsoft Virtual Technical Specialist(P-TSP) BizTalk, Azure
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.net<mailto:hedidin@edidingroup.net>

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>
[my-new-logosmall]<edidingroup.net>
Edidin-Group.com
Microsoft Partner Application Integration
hedidin@edidingroup.net
O: 224-360-3200
C: 630-306-1515
F: 847-816-8995
[Skypeicon_14px]847-393-8743<skype:8473938743?call>
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by HowardEdidin** [comment]
How do you run the Import Samples?




Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by mbaltus** [comment]
You can use the [localhost:49911]/Maintenance/Initialize command to reset the database and import the examples.

**Comment by HowardEdidin** [comment]
That worked.

Results:

Status: 100% Import completed! ERROR Importing DiagnosticReport 25... : Value cannot be null. Parameter name: key ERROR Importing NamingSystem 4.3.21... : Object reference not set to an instance of an object. ERROR Importing Practitioner 14... : Object reference not set to an instance of an object.



Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP
Microsoft Virtual Technical Specialist(P-TSP) BizTalk, Azure
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.net<mailto:hedidin@edidingroup.net>

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>
[my-new-logosmall]<edidingroup.net>
Edidin-Group.com
Microsoft Partner Application Integration
hedidin@edidingroup.net
O: 224-360-3200
C: 630-306-1515
F: 847-816-8995
[Skypeicon_14px]847-393-8743<skype:8473938743?call>
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by cknaap** [comment]
FYI: The errors are expected, nothing to worry about.

**Comment by HowardEdidin** [comment]
How would I go about adding support for STU3?

I need to support the Financial Resources.

On a side note, I am using Azure DocumentDB for the repository.   I will be creating a tutorial, published on the Azure site on how to do it.
The source code will be available

Thanks,


Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by cknaap** [comment]
DocumentDB is very interesting, I'd love to hear / read about it.

As for STU3: try to use the STU3 versions of the Hl7.Fhir packages, that will provide you with the new resources. Implementing new REST-interface features will have to be done by hand.

**Comment by HowardEdidin** [comment]
Where can I find the STU Packages?

Thanks,


Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by HowardEdidin** [comment]
I just found the package..

Thanks,


Howard S. Edidin MCTS, MCP
Senior Azure Solution Architect

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP – Data Platform
Microsoft Integration P-TSP (Healthcare and Life Sciences)
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
DocumentDB Wizard
TechNet Wiki Ninja



100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner |Cloud Solution Provider
Cloud Solutions | Data Platform & Analytics | Enterprise Integration

[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by cknaap** [comment]
On nuget: https://www.nuget.org/packages/Hl7.Fhir.STU3 and https://www.nuget.org/packages/Hl7.Fhir.Specification.STU3. All prerelease, so there's no warranty yet.
