### ISSUE TITLE
FormatException - spark-dstu2-master

### ISSUE THREAD

**Issue by HowardEdidin** [FirelyTeam/spark#113]
I am getting the following format exception.
GET:  http://hl7fhirserver.azurewebsites.net/fhir/_snapshot?id=10b5015a-63fb-4aab-93ef-e7a17b9d1848&start=0

`<OperationOutcome xmlns="http://hl7.org/fhir">
    <issue>
        <severity value="error" />
        <diagnostics value="FormatException: An error occurred while deserializing the WhenCreated field of class Spark.Engine.Core.Snapshot: ReadInt64 can only be called when CurrentBsonType is Int64, not when CurrentBsonType is Double." />
    </issue>
    <issue>
        <severity value="information" />
        <diagnostics value="   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)&#xD;&#xA;   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)&#xD;&#xA;   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)&#xD;&#xA;   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)&#xD;&#xA;   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.ReplyMessageBinaryEncoder`1.ReadMessage()&#xD;&#xA;   at MongoDB.Driver.Core.WireProtocol.Messages.Encoders.BinaryEncoders.ReplyMessageBinaryEncoder`1.MongoDB.Driver.Core.WireProtocol.Messages.Encoders.IMessageEncoder.ReadMessage()&#xD;&#xA;   at MongoDB.Driver.Core.Connections.BinaryConnection.&lt;ReceiveMessageAsync&gt;d__15.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at MongoDB.Driver.Core.WireProtocol.QueryWireProtocol`1.&lt;ExecuteAsync&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at MongoDB.Driver.Core.Servers.ClusterableServer.ServerChannel.&lt;ExecuteProtocolAsync&gt;d__24`1.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#xD;&#xA;   at MongoDB.Driver.Core.Operations.FindOperation`1.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at MongoDB.Driver.Sync.IOperationExtensions.Execute[TResult](IReadOperation`1 operation, IReadBinding binding, CancellationToken cancellationToken)&#xD;&#xA;   at MongoDB.Driver.MongoCollection.ExecuteReadOperation[TResult](IReadOperation`1 operation, ReadPreference readPreference)&#xD;&#xA;   at MongoDB.Driver.MongoCollection.FindOneAs[TDocument](FindOneArgs args)&#xD;&#xA;   at MongoDB.Driver.MongoCollection.FindOneAs[TDocument](IMongoQuery query)&#xD;&#xA;   at MongoDB.Driver.MongoCollection.FindOneByIdAs[TDocument](BsonValue id)&#xD;&#xA;   at Spark.Mongo.Store.MongoSnapshotStore.GetSnapshot(String snapshotid)&#xD;&#xA;   at Spark.Engine.Service.FhirServiceExtensions.PagingService.StartPagination(String snapshotkey)&#xD;&#xA;   at Spark.Engine.Service.FhirService.GetPage(String snapshotkey, Int32 index)&#xD;&#xA;   at Spark.Controllers.FhirController.Snapshot()&#xD;&#xA;   at lambda_method(Closure , Object , Object[] )&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;&gt;c__DisplayClass10.&lt;GetExecutor&gt;b__9(Object instance, Object[] methodParameters)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)&#xD;&#xA;   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" />
    </issue>
    <issue>
        <severity value="error" />
        <diagnostics value="FormatException: An error occurred while deserializing the WhenCreated field of class Spark.Engine.Core.Snapshot: ReadInt64 can only be called when CurrentBsonType is Int64, not when CurrentBsonType is Double." />
    </issue>`

**Comment by brianpos** [comment]
Was this occurring when trying to use Spark against the Azure DocumentDB?
(or a local MongoDB instance)

**Comment by brianpos** [comment]
This is due to the Microsoft JSON DateTimeOffset serializer being different to the Mongo one.
If you register the mongo one using this, it should work.

            // And register the BSON DateTimeOffsetSerializer
            BsonSerializer.RegisterSerializer<DateTimeOffset>(new DateTimeOffsetSerializer(BsonType.Document));

I tested this using the System History endpoint _history

**Comment by HowardEdidin** [comment]
Against a local MongoDB Instance

Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft MVP
Microsoft Virtual Technical Specialist(P-TSP) BizTalk, Azure
Microsoft HL7 Virtual Team
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.net<mailto:hedidin@edidingroup.net>

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>
[my-new-logosmall]<edidingroup.net>
Edidin-Group.com
Microsoft Partner Application Integration
hedidin@edidingroup.net
O: 224-360-3200
C: 630-306-1515
F: 847-816-8995
[Skypeicon_14px]847-393-8743<skype:8473938743?call>
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by HowardEdidin** [comment]
Where  do I add BsonSerializer.RegisterSerializer<DateTimeOffset>(new DateTimeOffsetSerializer(BsonType.Document));

**Comment by brianpos** [comment]
I've pushed my changes to a new branch in my for at https://github.com/brianpos/spark/tree/dstu2/MongoDB-update
Have a look in there for what I've done over the last day or so.
The Indexer code will need some attention/work before it is pulled into the dstu2/develop branch

**Comment by alexandrevribeiro** [comment]
I was facing the same exception but **it was solved** by registering the `DateTimeOffsetSerializer` as you said @brianpos. Well done!

And @HowardEdidin, I good place to register it is in the `Global.asax` of your application. 

And another thing to notice is that you also need to save your data into "MongoDB/Cosmos DB" with this serializer already registered. If not the queries won't work because the data were already saved using ` Microsoft DateTimeOffset serializer`.

**Comment by kennethmyhra** [comment]
This is not a problem anymore with later versions of the MongoDB libraries
