### ISSUE TITLE
Deadlock conflict with JsonFhirFormatter and Async DelegatingHandler

### ISSUE THREAD

**Issue by peterswallow** [FirelyTeam/spark#13]
I'm using your JsonFhirFormatter in my webapi application.

I've created an async DelegatingHandler which saves the response content to the database, but for some reason it keeps dead locking. I'm not certain which code is causing it (probably mine), but wondered if you had experienced this before?

This is the sample code I'm using for my Handler:

```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
                                                           CancellationToken cancellationToken)
    {
        var response = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);

        string content = "";
        if (response.Content != null)
        {
            var bytes = await response.Content.ReadAsByteArrayAsync().ConfigureAwait(false);
            content = Encoding.UTF8.GetString(bytes);    
        }

        //SAVE AUDIT TO DATABASE!

        return response;
    }
```

It seems to lock on the .ReadAsByteArrayAsync(). I'm not sure the .ConfigureAwait(false) is absolutely necessary, but seemed to resolve another deadlock issue I was having.

It might be useful, for me and others to include an Auditing handler in your server, as this could be a common scenario.

**Comment by mharthoorn** [comment]
Will treat issue as: "Add an Audit handler"
