### ISSUE TITLE
Read API is not returning the latest resource

### ISSUE THREAD

**Issue by kennethmyhra** [FirelyTeam/spark#132]
Moving discussion of https://github.com/ewoutkramer/fhir-net-api/issues/764 here

**Comment by santoshjami** [comment]
Ken - 

In your previous comment you mentioned that,"my impression is that you are posting a Bundle with Patient, Document, DiagnosticReport effectively using the Transaction operation on the API?"
Do you have an example API call to post the bundle as transaction? I don't think that I used Transactions on my end.

**Comment by kennethmyhra** [comment]
Yes, would like to know how you interact with the API. Some examples of your code when you create a Patient, DiagnosticReport etc would be helpful.

Also post the version number of Spark you are using.

**Comment by kennethmyhra** [comment]
@santoshjami I have contacted you over at chat.fhir.org sharing some scripts that could help us further investigate the issue.

**Comment by kennethmyhra** [comment]
Closing issue not able to reproduce, reopen if needed.
