### ISSUE TITLE
Migrate libraries to dotnet standard

### ISSUE THREAD

**Issue by kennethmyhra** [FirelyTeam/spark#133]
Goal: target lowest possible dotnet standard libraries

**Comment by aabuhasan** [comment]
Any idea when this can be ready, please?

**Comment by kennethmyhra** [comment]
I'm working on this, still in an early phase so I do not want to commit to a date for a release yet

**Comment by kennethmyhra** [comment]
@aabuhasan I have pushed two pre-release NuGet packages based on netstandard2.0 which supports .net core.

If you want to try out the packages that supports R4 you can add Spark.Engine.R4 and Spark.Mongo.R4 with version number 1.3.0-alpha01. For STU3 replace R4 with STU3, and same goes for DSTU2.

There is an example of a .net core implementation using those packages in the branches r4/develop (R4), stu3/develop (STU3) and develop (DSTU2) called [Spark.NetCore](https://github.com/FirelyTeam/spark/tree/r4/develop/src/Spark.NetCore)

**Comment by aabuhasan** [comment]
@kennethmyhra I will try it, thank you so much.
