### ISSUE TITLE
Microsoft.net FHIR Hl7.Fhir.STU3 Client

### ISSUE THREAD

**Issue by congming** [FirelyTeam/spark#135]
Server:Open source from https://github.com/FirelyTeam/spark
Deploy to Microsoft IIS

VS2017 Client: HL7.Fhir.STU3

Hl7.Fhir.Rest.FhirOperationException: 'Operation was unsuccessful, and returned status InternalServerError. OperationOutcome: Overall result: FAILURE (1 errors and 0 warnings)

 [ERROR] (no details)(further diagnostics: Endpoint returned a body with contentType 'text/html', while a valid FHIR xml/json body type was expected. Is this a FHIR endpoint?).'

Client:
![image](https://user-images.githubusercontent.com/7532315/51300106-b90a7480-1a65-11e9-9fcc-e87580cb1e2a.png)

Server Tracing as following:

![image](https://user-images.githubusercontent.com/7532315/51299998-51ecc000-1a65-11e9-9072-93505977c26a.png)

**Comment by congming** [comment]
Server:Open source from https://github.com/FirelyTeam/spark
Deploy to Microsoft IIS

VS2017 Client: HL7.Fhir.STU3

**Comment by kennethmyhra** [comment]
Change
`
Dim Client As New FhirClient("http://localhost:49911/")
`
to
`
Dim Client As New FhirClient("http://localhost:49911/fhir")
`

**Comment by kennethmyhra** [comment]
Reopen if supplied solution is not sufficient
