### ISSUE TITLE
How Patient Instance own Observation Instances

### ISSUE THREAD

**Issue by congming** [FirelyTeam/spark#138]
I have no idea about How to ...

let Patient Instance own Observation Instances?
From Resourcelist-FHIR v4.0.0, patient class has many properties and which one can be a Observation collection(list)

Am I thinking wrong way? perhaps Observation have a property point to specific Patient Instance??

**Comment by kennethmyhra** [comment]
You reference the Patient from an Observation - http://hl7.org/fhir/observation-definitions.html#Observation.subject

To add onto your question, if you later want to retrieve all observations for a patient from the fhir server look into reference parameters in the search documentation at: http://hl7.org/fhir/search.html#reference

Not sure if you are aware, but there is a community chat where these kind of questions are better asked http://chat.fhir.org
