### ISSUE TITLE
Installation instruction is not correct

### ISSUE THREAD

**Issue by yunwwang** [FirelyTeam/spark#139]
the installation document states 

"10.	Run the command below in a Command Line, as Administrator. It will register MongoDb as a Windows Service.
c:\Program   Files\MongoDB\Server\3.2\bin>mongod.exe --config "C:\Spark\MongoDB\Config\SparkMongoDB.cfg" --installLocal Firewall"

The "--installLocal Firewall" is not a valid mongod command option.

**Comment by kennethmyhra** [comment]
Nice catch, I'll probably deprecate the file and redirect it to our wiki https://github.com/FirelyTeam/spark/wiki/Deploy-Spark.
