### ISSUE TITLE
Search by string parameter doesn't work correctly if string starts at "eb"

### ISSUE THREAD

**Issue by SWATOPLUS** [FirelyTeam/spark#146]
Doesn't work (returns 400)
http://127.0.0.1:5000/fhir/Practitioner?_id%3Aexact=eb3e0a10-dc5d-4d1d-9d57-21e4a3dcb1ab%2Cf1a69cbc-61c7-4b70-951b-5260ecef06fa

Works!
http://127.0.0.1:5000/fhir/Practitioner?_id%3Aexact=06b70ac5-c659-4464-ad6e-6f3d78640141%2C129163ec-04d1-4b14-a2f0-c0309810d24b

Criterium.Parse() method doesn't work correctly. Private method Criterium.findComparator parse prefix of value. But it shouldn't be called with string typed parameter.

According to https://www.hl7.org/fhir/stu3/search.html#prefix

For the ordered parameter types of **number, date, and quantity**, a prefix to the parameter value may be used to control the nature of the matching.

It means that type of the parameter should be determined before extracting a prefix.

I will submit PR which pratially solves this issue, but we need common solution.

**Comment by kennethmyhra** [comment]
@SWATOPLUS, thanks for reporting this, I looked further into it and it should be fixed by #149. I will forward those fixes to STU3 and R4 since the develop branch is DSTU2. Please do verify at your availability.
