### ISSUE TITLE
IndexingService not indexing SearchParameters referring to arrays of type Resource

### ISSUE THREAD

**Issue by Crownie88** [FirelyTeam/spark#155]
When searching for a Bundle that is of the type document and has a composition with that contains a string it will not give any items even though there are plenty of bundles that should meet the requirement.

Search: 
\<BaseUrl>/Bundle?type=document&composition.title:contains=\<SubString>
\<BaseUrl>/Bundle?composition.title:contains=\<SubString>

**Comment by kennethmyhra** [comment]
@Crownie88 I've updated the title in accordance with the findings on this one

**Comment by Crownie88** [comment]
@kennethmyhra Perfect, thanks. I tried looking for these arrays since I thought this was the case but couldnt find the source of the search parameters.
