### ISSUE TITLE
CreateMongoDatabase support SCRAM-SHA-1 and other authentication mechanisms.

### ISSUE THREAD

**Issue by aabuhasan** [FirelyTeam/spark#162]
`var mongoUrl = new MongoUrl(url);
			string authMechanism = "SCRAM-SHA-1";
			string authDB = "admin";

			MongoClientSettings settings = new MongoClientSettings();

			if (mongoUrl.Username != null && mongoUrl.Password != null)
			{
				MongoInternalIdentity internalIdentity = new MongoInternalIdentity(authDB, mongoUrl.Username);
				PasswordEvidence passwordEvidence = new PasswordEvidence(mongoUrl.Password);
				MongoCredential credential = new MongoCredential(
					authMechanism,
					internalIdentity,
					passwordEvidence);
				List<MongoCredential> credentials = new List<MongoCredential>() { credential };
				 
				// comment this line below if your mongo doesn't run on secured mode
				settings.Credentials = credentials;
			}

			settings.Server = mongoUrl.Server;

			MongoClient client = new MongoClient(settings);
			 
			return client.GetServer().GetDatabase(mongoUrl.DatabaseName);`

Need to pass the following:
authMechanism
authDB

**Comment by kennethmyhra** [comment]
You would need to add those Authentication Options to the connection string as described here: https://docs.mongodb.com/manual/reference/connection-string/#authentication-options

**Comment by aabuhasan** [comment]
Thanks, it worked

**Comment by kennethmyhra** [comment]
That's great!
