### ISSUE TITLE
Oracle database support

### ISSUE THREAD

**Issue by aabuhasan** [FirelyTeam/spark#163]
How can I confiure Spark server to work with Oracle & SQL Server as Storage?

**Comment by kennethmyhra** [comment]
While this is most certainly possible there is no official package for this right now. There is some unfinished code for Sql using Entity Framework here: https://github.com/FirelyTeam/spark/tree/master/src/Spark.Store.Sql if you want to take a look.

In addition to this you can use Spark as a facade letting it handle the request/response pipeline and you as the implementer taking care of storage, search etc. This should hopefully be easier with the new packages I'm making available.

**Comment by shirajmomin** [comment]
Is this "https://github.com/FirelyTeam/spark/tree/master/src/Spark.Store.Sql" working now?

**Comment by kennethmyhra** [comment]
@shirajmomin No it is not, also the project at that location is quite old and was never finished. If some type of that work would start again it would probably start from scratch.
