### ISSUE TITLE
Filter task based on focus

### ISSUE THREAD

**Issue by aabuhasan** [FirelyTeam/spark#169]
It seems like task focus property is not stored on searchindex collection.

**Comment by kennethmyhra** [comment]
Thanks for reporting this.

I investigated this and found that the index was written to the searchindex collection, but there's an issue with the search engine that probably made your search fail. I have pushed a hotfix to the master branches and a made a new release v1.2.1, see [Releases](https://github.com/FirelyTeam/spark/releases), which should resolve this issue.
