### ISSUE TITLE
Not returning json when Content-Type Header is application/fhir+json

### ISSUE THREAD

**Issue by pwachira** [FirelyTeam/spark#177]
curl -v  -H " application/fhir+json; charset=utf-8" http://spark.kufu.no/fhir/CapabilityStatement

returns xml - is this expected?

**Comment by pwachira** [comment]
its actually a html table - closing the issue - I was able to get json output using 
curl -v  -H " application/fhir+json; charset=utf-8" http://spark.kufu.no/fhir/Patient/237/_history/1\?_format\=json

**Comment by kennethmyhra** [comment]
Btw, your curl statement is not setting the Accept header, it should be like this:
`curl -v -H "Accept: application/fhir+json; charset=utf-8" http://spark.kufu.no/fhir/CapabilityStatement`
