### ISSUE TITLE
Problem when publishing with precompile setting

### ISSUE THREAD

**Issue by R0Wi** [FirelyTeam/spark#190]
Hi and thank you for your nice .NET implementation of the FHIR API. 

I'm working with the `r4/master` branch and i have a problem when trying to publish the `Spark` webapplication via a ASP.NET publishing profile, which uses the `Precompile during publishing` option. The project compiles but when `aspnet_compiler.exe` tries to compile the views i get this error:

```
Der Typname 'MediaTypeHeaderValue' wurde nicht gefunden. Dieser Typ wurde an Assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' weitergeleitet. Fügen Sie ggf. einen Verweis auf die Assembly hinzu.
```

So in english it's something like
```
The Typename 'MediaTypeHeaderValue' was not found. This type was redirected to the assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Please add a reference to this assembly.
```

I saw that you added two assembly redirects so `System.Net.Http` in your `Web.config`:
https://github.com/FirelyTeam/spark/blob/0b7a60de2a9af9cb0dc3c6f2cd2c93cfe0316507/src/Spark/Web.config#L163
https://github.com/FirelyTeam/spark/blob/0b7a60de2a9af9cb0dc3c6f2cd2c93cfe0316507/src/Spark/Web.config#L295

So beside the fact you should only do a redirect once, even if i delete the second one i get the mentioned error. Could you imagine what's the problem?

**Comment by kennethmyhra** [comment]
Thanks for reporting this @R0Wi! I do not have an immediate solution to the problem, will have to look into it.

By the way, just want to mention that there is a .net core example in the repository located in folder Spark.Web as well as some documentation on how to set up your own FHIR server from scratch using the Spark NuGet packages here: http://firelyteam.github.io/spark/quickstart. It also includes a simple example that you can finde here: https://github.com/kennethmyhra/spark-example

**Comment by kennethmyhra** [comment]
@R0Wi could you test branch [fix/assembly-conflicts](https://github.com/FirelyTeam/spark/tree/fix/assembly-conflicts) in PR #192 and give me feedback if it fixes your problem. My tests publishing to a local IIS installation seems to work with those changes.

**Comment by R0Wi** [comment]
@kennethmyhra this fixed my issue. I tried it with different settings for precompilation in the publish dialog.

![image](https://user-images.githubusercontent.com/19730957/71876196-83ebac00-3126-11ea-835f-145860ad8760.png)
![image](https://user-images.githubusercontent.com/19730957/71876262-a2ea3e00-3126-11ea-93c7-d5e7e80d1411.png)

The only thing i noticed was a compiler warning 
```
(0): warning : The following assembly has dependencies on a version of the .NET Framework that is higher than the target and might not load correctly during runtime causing a failure: Spark, Version=14.8.0.0, Culture=neutral, PublicKeyToken=null. The dependencies are: System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089; System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. You should either ensure that the dependent assembly is correct for the target framework, or ensure that the target framework you are addressing is that of the dependent assembly.
```

Thanks for this fix !

**Comment by kennethmyhra** [comment]
Yep, it probably has to do with Spark.Engine which targets both net461 and netstandard2.0. I see the same compiler warning and have tried some fixes to get around it, so far without any luck and since it currently works for both you and me I think I will leave it for the time being.

Thanks for testing the fix and reporting back 👍

**Comment by R0Wi** [comment]
Thank you too for fixing :-)

Just because i'm curious: could you tell us, what exactly you did in this PR ?

**Comment by kennethmyhra** [comment]
I did a `Update-Package -Reinstall -IgnoreDependencies` from the Package Manager Console in VS, this retargeted the Spark project from net46, which it depended on earlier, to net461.

In addition because of the error messages when publishing and the duplicates under the assemblyBinding node in Web.config (and it generally looked messed up) I deleted all of the assembly bindings and let VS regenerate them.

**Comment by kennethmyhra** [comment]
Fix has been pushed to branches master (DSTU2),  stu3/master (STU3) and r4/master (R4)
