### ISSUE TITLE
Custom Resources in Spark

### ISSUE THREAD

**Issue by dattachandan** [FirelyTeam/spark#196]
Hi team,

Is there a way to use custom resources generated by Forge in a Spark server, as is it done in Vonk in the example with the appsettings.instance.json file:
- https://blog.fire.ly/2019/05/03/custom-resources-in-vonk/
- http://docs.simplifier.net/vonk/features/conformanceresources.html

**Comment by kennethmyhra** [comment]
Hey @dattachandan 

Currently there isn't a configurable way to do this, and I haven't looked deeply into how this could be done with  https://github.com/FirelyTeam/fhir-net-api which both Vonk and Spark uses.

I do though think that using ISourceNode from the fhir-net-library would make it possible to support custom resources in Spark.
