### ISSUE TITLE
Windows 2019 container instructions

### ISSUE THREAD

**Issue by dattachandan** [FirelyTeam/spark#197]
Hi team,

Has anyone tried to run the mongodb docker-compose on a windows 2016/2019 server?

The instructions below won't work because it requires windows 10 professional running linux hyperv containers. I can't see a windows servercore mongodb image in the dockerfile [code](https://hub.docker.com/layers/sparkfhir/mongo-spark-r4/latest/images/sha256-1b46065359eceed3183fa419c72959f9a8936edc96fcb7d6f6e3060a41ebd1fa)

`Mac OS X / Windows: curl 'https://raw.githubusercontent.com/firelyteam/spark/develop/dockers/spark-r4/docker-compose.yml' > docker-compose.yml && docker-compose up`

**Comment by kennethmyhra** [comment]
I got some help on the docker-part so I am not well versed yet in the docker/container world.

If you have any suggestions to how we could make a windows container available, it would be greatly appreciated.

**Comment by Massy1989** [comment]
Those example commands need updated in getting started...
because "https://raw.githubusercontent.com/firelyteam/spark/develop/dockers/spark-r4/docker-compose.yml" doesn't even exist anymore.

**Comment by kennethmyhra** [comment]
@Massy1989 example commands updated
