### ISSUE TITLE
Docker-compose file

### ISSUE THREAD

**Issue by armanpetrosyan23** [FirelyTeam/spark#242]
Hello, i want to up your services via docker compose but docker-compose up not successful 
I always see this state
![image](https://user-images.githubusercontent.com/35919382/88390903-35ec7c00-cdca-11ea-8842-c62b3ca16f08.png)

**Comment by kennethmyhra** [comment]
@armanpetrosyan23 I can run this on Windows 10 without any problems. What version of Windows are you trying to run docker-compose?

**Comment by armanpetrosyan23** [comment]
@kennethmyhra  Thank you for answering, i try it to run on Windows 10 x64, I think maybe you have already pulled image in yor local docker registry, becouse i tried it on many dockers and recive same error
![image](https://user-images.githubusercontent.com/35919382/88464575-01adb400-cecd-11ea-939a-eca4802df6d6.png)

**Comment by kennethmyhra** [comment]
I'm pretty sure I did not have the images locally:

![image](https://user-images.githubusercontent.com/248795/88464821-1afb3400-cebe-11ea-9010-03445ea2bfdd.png)

I got the same version of docker and docker-compose that you listed there

**Comment by kennethmyhra** [comment]
Btw, I found this issue https://github.com/docker/for-win/issues/6192. Could this be relevant for you as well? (I noticed the unexpected EOF in your docker pull)

**Comment by losolio** [comment]
@armanpetrosyan23 Could you try to add the verbose flag, to see if more information is provided? I.e. `docker-compose up --verbose`.

**Comment by kennethmyhra** [comment]
Closing this as non-reproducible, please reopen if problem persists and further information is available
