### ISSUE TITLE
Does not include entries when providing multiple _include arguments

### ISSUE THREAD

**Issue by pieteckhart** [FirelyTeam/spark#268]
**Describe the bug**
It should be possible to provide multiple _include arguments to a FHIR request.

As stated on https://www.hl7.org/fhir/search.html#include

> _include and _revinclude parameters do not include multiple values. Instead, **the parameters are repeated for each different include criteria**.

**To Reproduce**
Given an observation that has both related-target and a specimen make a call to Observation/?_include=Observation:related-target&_include=Observation:specimen

**Expected behavior**
3 entries

**Actual behavior**
Just the single Observation entry without the relating entries.

When I try the _include arguments in two separate calls they do work individually:
Observation/?_include=Observation:specimen
Observation/?_include=Observation:related-target

**Comment by kennethmyhra** [comment]
Thanks, probably a bug from what you are describing. Moving it into current iteration

**Comment by pieteckhart** [comment]
I've done some digging and found out the cause is the way the querystring is parsed.
The SearchParams returns a single Include that has both values comma seperated. So in this case that would be: "Observation:related-target,Observation:specimen"

I've successfully tested this with the folowing workaround in the HttpRequestExtensions class:

``` 
        public static SearchParams GetSearchParams(this HttpRequestMessage request)
        {
            var parameters = request.TupledParameters().Where(tp => tp.Item1 != "_format");
            var searchCommand = SearchParams.FromUriParamList(parameters);

           var includes = new List<string>();
            foreach (var inc in searchCommand.Include)
            {
                includes.AddRange(inc.Split(','));
            }

            searchCommand.Include.Clear();
            foreach (var inc in includes)
            {
                searchCommand.Include.Add(inc);
            }

            return searchCommand;
        }
```

It seems that the bug is not a spark bug but something that should be resolved in https://github.com/FirelyTeam/fhir-net-api where the SearchParams class lives.

Should I create a ticket there?

**Comment by pieteckhart** [comment]
The other way around (SearchParams to query string) has already been discussed here: https://github.com/FirelyTeam/fhir-net-api/issues/501

**Comment by brianpos** [comment]
I'm pretty sure I had this bug in the sqlonfhir server, and subsequently the fhir facade project. If you test it in that project you should be able to locate where the fix is needed.
From memory it was in the. ToTupledParameters that messed things up from one of the net framework librarys that parsed out a named parameter dictionary, instead of key value pairs
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore/HttpHeadersExtensions.cs

**Comment by pieteckhart** [comment]
You are correct, It seems that the bug is only in the .Net Framework version of the TupledParameters method.

My fix would be splitting all argument values on ",":
```
        public static List<Tuple<string, string>> TupledParameters(this HttpRequestMessage request)
        {
            var list = new List<Tuple<string, string>>();

            NameValueCollection queryNameValuePairs = request.RequestUri.ParseQueryString();
            foreach (var currentKey in queryNameValuePairs.AllKeys)
            {
                list.AddRange(queryNameValuePairs[currentKey].Split(',').Select(v => Tuple.Create(currentKey,v)));
            }
            return list;
        }
```

The only thing that  can possibly lead to problems is single query parameters that need a "," in its value. In order to fix this we need to manually parse the querystring and not use RequestUri.ParseQueryString.

Can I create a pull request for the above fix?

**Comment by kennethmyhra** [comment]
Absolutely! Please add tests that proves the new behavior

**Comment by kennethmyhra** [comment]
Another thing, use master as the base branch. I will forward your changes to stu3/master and r4/master

**Comment by pieteckhart** [comment]
Unfortunately the purposed fix would break  OR search parameters as they use a comma to specify both cases:
https://www.hl7.org/fhir/search.html#combining

We need to look for a alternative solution that parses the querystring in a way that would differentiate between:
?arg=1&arg=2
and
?arg=1,2

**Comment by pieteckhart** [comment]
Fixed :)
