### ISSUE TITLE
Some problems with Synchronous IO in asp.net core

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#272]
> In some cases, this error occurs : Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.

some reference:
https://github.com/dotnet/aspnetcore/issues/4707
https://github.com/dotnet/aspnetcore/issues/13834
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#avoid-using-synchronous-readwrite-overloads-on-httprequestbody-and-httpresponsebody

**Comment by whyfate** [comment]
It's will be fix by .net5 or asp.net core 3.x,We can use recommended workaround.
```csharp
using (var reader = new StreamReader(context.Request.Body, Encoding.UTF8, leaveOpen: true))
{
   var body = await reader.ReadToEndAsync();
}
```

**Comment by kennethmyhra** [comment]
Some more context: https://github.com/FirelyTeam/spark/commit/d616cb0dc6beb7bed166559b0ffbf4c056cf92df#r42116699

**Comment by kennethmyhra** [comment]
@whyfate I looked into this and as far as I understand from the discussions in the referenced threads this has probably to do with the spotty network connection you mentioned. Thoughts regarding this?

**Comment by whyfate** [comment]
@kennethmyhra Yes, I've only seen this happen when the network is unstable.Still, is it better to use asynchronous IO?

**Comment by kennethmyhra** [comment]
@whyfate Sorry for the delay in answering. We will probably move more and more to asynchronous IO, so yes it will stay async.

I will add in the leaveOpen argument in the next version which should go out any day so that should hopefully fix your issue
