### ISSUE TITLE
r4/master branch - Spark project isn't loading

### ISSUE THREAD

**Issue by deepakgauda-dk** [FirelyTeam/spark#278]
Hi Team,

The moment i take the latest changes of 'r4/master' branch, Spark.csproj isn't loading within the spark solution. Looks like recently made changes on references is causing the issue in Spark class library/project.

**To Reproduce**
1. Pull changes or clone the repository (switch to 'r4/master' branch)
2. Open the solution in visual studio 2019
3. Notice 'Spark' project unloaded

Earlier the Spark project used to be loaded as expected.

Attaching screenshot for the reference:
![image](https://user-images.githubusercontent.com/54955876/93374850-ef207d00-f874-11ea-9a79-d54b2faa9d31.png)

Recent changes are primarily on the versions of referenced libraries like Microsoft.Owin *, MongoDB.Driver *, Hl7.Fhir * etc. Therefore, having the same versioned libraries in the project would fix the issue.

Please let me know is this issue occurring for others too ? and may i know when can we expect the fix/work around for the same.

**Comment by kennethmyhra** [comment]
Thanks for reporting @deepakgauda-dk. The referenced commit 2fe6498 fixes it.
