### ISSUE TITLE
Indexing elemens for search

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/spark#30]
In the C# object model there are elements for which the name end on "\_" (like AppointmentResponse.ParticipantStatus).  If these paths occur in the definition of search parameters, the harvester will not be able to find the appropriate element on the object model.  Easy fix would be for the harvester to re-try to find a property suffixed with "\_" when a property is not found.

**Comment by mharthoorn** [comment]
The harvesting has been rewritten since.

**Comment by brianpos** [comment]
You should look into using the fluentpath implementation for extraction. I have a unit test in the .net fhir client that demonstrates this (and is going into sqlonfhir too)

**Comment by kennethmyhra** [comment]
STU3 and R4 has been rewritten to use FhirPath for indexing (#171) will be part of release 1.3
