### ISSUE TITLE
PATCH support

### ISSUE THREAD

**Issue by andy-a-o** [FirelyTeam/spark#302]
**Is your feature request related to a problem? Please describe.**
http://www.hl7.org/fhir/STU3/http.html#patch

**Describe the solution you'd like**
PATCH method is supported as described in the spec.

**Failed tests**
`ConnectathonPatchTrackTest`

**Comment by jjrdk** [comment]
I created a [draft PR](https://github.com/FirelyTeam/spark/pull/341) to propose a way to add support for patch.

**Comment by jjrdk** [comment]
@kennethmyhra  Can we close this issue now that #341 has been merged?

**Comment by kennethmyhra** [comment]
Absolutely

**Comment by andy-a-o** [comment]
http://www.hl7.org/fhir/R4/http.html#patch

> The body of a PATCH operation SHALL be either:
> a JSON Patch  document with a content type of application/json-patch+json
> an XML Patch  document with a content type of application/xml-patch+xml
> a FHIRPath Patch parameters resource with FHIR Content Type

for now, it seems that only FHIR Patch was implemented. Can't really say this issue is solved... Can't re-enable tests because of that (tests send JSON patch).

**Comment by andy-a-o** [comment]
#384
