### ISSUE TITLE
Search by some Reference is not working.

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#340]
**Describe the bug**
Search by some Reference is not working.

**To Reproduce**
Resources written
```json
{
    "resourceType": "ConceptMap",
    "sourceUri": "http://ValueSet.fhir.org/test",
}
```

GET `/fhir/ConceptMap?source-uri=http://ValueSet.fhir.org/test`

**Expected behavior**
Return the valid results.

**Comment by whyfate** [comment]
The `sourceUri` in index store is `http://ValueSet.fhir.org/test`,but the query is normalized to `http://valueSet.fhir.org/test`.

**Comment by kennethmyhra** [comment]
Currently hotfix in Spark R4 branch. Related issue here: https://github.com/FirelyTeam/firely-net-sdk/issues/1643

**Comment by whyfate** [comment]
Hey @kennethmyhra ,This problem may still exist,
The `CodeSystem` resource has a `url` attribute. The type of query parameter is `uri`. It is normalize when writing to the index store, but not when querying.Only the `reference` type is normalize when querying. 
https://github.com/FirelyTeam/spark/blob/8246fd3114f9884f301748ca62a9412c115d6298/src/Spark.Mongo/Search/Searcher/MongoSearcher.cs#L256-L263
https://github.com/FirelyTeam/spark/blob/8246fd3114f9884f301748ca62a9412c115d6298/src/Spark.Engine/Search/ElementIndexer.cs#L197-L205

such as:
```json
{
    "resourceType": "CodeSystem",
    "url": "http://CodeSystem.fhir.org/test",
}
```
```
GET /fhir/CodeSystem?url=http://CodeSystem.fhir.org/test
```

**Comment by kennethmyhra** [comment]
@whyfate can you check out the fix I added to both STU3 and R4 branch and see if it fixes this issue

**Comment by whyfate** [comment]
I tested with the latest R4 branch code,and it did not solve it.
Here is my test data
```json
{
    "resourceType": "CodeSystem",
    "id": "gender",
    "url": "http://CodeSystem.fhir.org/gender",
    "name": "gender",
    "title": "gender",
    "status": "draft",
    "publisher": "fhir.org",
    "description": "gender",
    "content": "complete",
    "concept": [
        {
            "code": "1",
            "display": "Male"
        },
        {
            "code": "2",
            "display": "Female"
        }
    ]
}
```
```
GET /fhir/CodeSystem?url=http://CodeSystem.fhir.org/gender
```
The `uri` property is normalized when storing it,but when querying, only `reference` is normalized , not `uri`.
I think this is the reason for the problem.

**Comment by kennethmyhra** [comment]
That's strange. I retested it again and it works on my end. Are you sure that you have this commit https://github.com/FirelyTeam/spark/commit/07fd9ebd676bfc90834c5e489b5c1ebff410ce2b when you are trying?

**Comment by whyfate** [comment]
Sorry,my code version is 1.5.5.It's not the latest.I will pull the latest code.
I only saw the commit [84d3a31d](https://github.com/FirelyTeam/spark/commit/84d3a31d1b0e0b9a8dd6e94475d28247265159ca) mentioned earlier.

**Comment by whyfate** [comment]
@kennethmyhra  I pull the latest code,it's resolved,thanks.
