### ISSUE TITLE
Got an 400 Error while PUTting a condition resource

### ISSUE THREAD

**Issue by billkuojhgf** [FirelyTeam/spark#356]
**Describe the bug**
I've tried to put some condition resources into the Spark server, but it responded an error with code 400, and show 
`"Body parsing failed: Type checking the data: Encountered unknown element 'encounter' at location 'Resource.encounter[0]' while parsing"` information.

**To Reproduce**

***Resource written***
```{
  "id": "EC957316-01cond",
  "code": {
    "coding": [
      {
        "code": "C50911",
        "system": "http://hl7.org/fhir/sid/icd-10"
      }
    ]
  },
  "encounter": {
    "id": "EC957316",
    "reference": "Encounter/EC957316",
    "type": "Encounter"
  },
  "recordedDate": "2036-03-18T00:00:00",
  "subject": {
    "id": "OP957316",
    "reference": "Patient/OP957316"
  },
  "resourceType": "Condition"
}
```
`PUT "http://localhost:5555/fhir/Condition/EC957316-1cond"`

**Expected behavior**
Return 201 code

**Screenshots**
https://imgur.com/a/nuDrvjl

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**
I'm wondering if that is a bug or I just do something wrong.
And thanks for all these works, hope to get your reply soon.

**Comment by kennethmyhra** [comment]
You are posting what I assume is an R4 resource (`encounter` is an element that was added in R4), but running a version of Spark that is built from the `stu3/master` branch. If you switch to the `r4/master` you should get the expected behaviour

**Comment by billkuojhgf** [comment]
Oh oops, yeah i've installed the wrong built.
It works after installing the R4 resources. Thanks for the answer.

**Comment by kennethmyhra** [comment]
Great 👍🏻
