### ISSUE TITLE
Search with HumanName

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#357]
**Describe the bug**
I read the document about [querying with the patient's name](http://hl7.org/fhir/patient.html#search),and it said that we can query through `family, give, prefix, suffix, suffix, and/or text`,but only family and given are implemented in the `spark` code
https://github.com/FirelyTeam/spark/blob/d1c29b54c8a5eb2c147126c1983151f041a511e2/src/Spark.Engine/Search/ElementIndexer.cs#L439-L454
Is there any special purpose?

**Comment by kennethmyhra** [comment]
Definitely, seems we need to update that index
