### ISSUE TITLE
Getting "MongoAuthenticationException: Server sent an invalid nonce" errors on concurrent operations

### ISSUE THREAD

**Issue by karlmdavis** [FirelyTeam/spark#377]
**Describe the bug**
Spark goes boom when running some concurrent operations. Specifically, it returns errors like the following:

```
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "diagnostics": "MongoAuthenticationException: Server sent an invalid nonce."
    }
  ]
}
```

**To Reproduce**
This is roughly how I'm reproducing the error, though I imagine that the specifics aren't _super_ relevant:
1. Run the R4 server via Docker.
2. Submit multiple concurrent resource `POST`s (I happen to be submitting `Organization`s, though I doubt that matters).
3. Rinse and repeat.
4. Watch it go boom.

**Expected behavior**
Don't go boom.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: N/A (I'm submitting data via raw HTTP ops)
 - Version: N/A

**Additional context**
From a quick Google, I'd guess that the issue is fixable by updating your C# Mongo client library, to catch this fix: <https://jira.mongodb.org/browse/CSHARP-3196>.

**Comment by kennethmyhra** [comment]
Thanks for bringing this to my attention, @karlmdavis. Still, it's a bit annoying since we in 1.5.4 should be at MongoDB libraries 2.12.

Do you have a tool or script that can easily reproduce this?

**Comment by karlmdavis** [comment]
> it's a bit annoying since we in 1.5.4 should be at MongoDB libraries 2.12.

Darn it, my bad. I ran a `docker-compose pull` and, wouldn't you know it? The problem disappeared. The previous version of Spark that I had would have been from... last October or so? Regardless, my apologies for the hassle & distraction.
