### ISSUE TITLE
Security Disclosure Contact

### ISSUE THREAD

**Issue by ZacharyMinneker** [FirelyTeam/spark#378]
Hello! I’m a security engineer and researcher at Security Innovation. I’ve identified a security vulnerability in the Spark implementation that I would like to to responsibly and securely disclose and coordinate resolving this issue. Can you let me know to whom and in what form I should send this information? Is there someone I should contact via email?

**Comment by kennethmyhra** [comment]
You can contact info@incendi.no

**Comment by ZacharyMinneker** [comment]
Ok, great, thank you very much.
