### ISSUE TITLE
Server won't accept resources that already have an ID

### ISSUE THREAD

**Issue by karlmdavis** [FirelyTeam/spark#381]
**Describe the bug**

The FHIR specification states the following, in <http://hl7.org/fhir/http.html#create>:

> The resource does not need to have an id element (this is one of the few cases where a resource exists without an id element). If an id is provided, the server SHALL ignore it.

However, when trying to post a resource with an ID, Spark returns an HTTP `400` error with the following body:

```
{
  "resourceType": "OperationOutcome",
  "issue": [{
    "severity": "error",
    "diagnostics": "The request should not contain an id"
  }]
}
```

**To Reproduce**
`POST` any resources that already has an ID (e.g. a resource created by Synthea).

**Expected behavior**
The server should accept the `POST`ed resource without error, assigning it an ID as usual.

**Additional context**
I haven't verified this is in a recent version, so my apologies if it's no longer an issue.

**Comment by karlmdavis** [comment]
May be (somewhat) related to #296.

**Comment by kennethmyhra** [comment]
@karlmdavis just tried to reproduce this, but not able to. Can you verify with the latest version to see if this is still an issue?

**Comment by kennethmyhra** [comment]
This was fixed in the following commit: https://github.com/FirelyTeam/spark/commit/0253e722344bd1bd5c9ebebabc5be38f329b1cbf. My recent tests also shows that this is no longer an issue.
