### ISSUE TITLE
Search by `date` question

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#390]
**Describe the bug**
 `date` cannot be `le` to query.

**To Reproduce**
// Such as `Schedule`:
```json
{
    "resourceType": "Schedule",
    "planningHorizon": {
        "start": "2021-06-01T09:00:00",
        "end": "2021-06-01T12:00:00"
    }
}
// search by date
GET /fhir/Schedule?date=ge2021-06-01T09:00:00    // have results.
GET /fhir/Schedule?date=le2021-06-01T12:00:00    // no result.
```

**Comment by kennethmyhra** [comment]
@whyfate as always appreciate your reports (and PRs)! I'll have a look at this

**Comment by whyfate** [comment]
@kennethmyhra https://github.com/FirelyTeam/spark/blob/212d071003bc1a57affe7aaceacef133108a9b00/src/Spark.Mongo/Search/Searcher/CriteriaMongoExtensions.cs#L460-L462
I don't know if there is a special design.

**Comment by whyfate** [comment]
Here's another question:
```json
{
    "resourceType": "Schedule",
    "planningHorizon": {
        "start": "2021-06-01T00:00:00",
        "end": "2021-06-01T08:00:00"
    }
}
// search by date
GET /fhir/Schedule?date=ge2021-06-01    // no result.
```
Because my current time zone is `+08:00`,and when I write to store, it's UTC,The local time zone is not considered when 
 `ge2021-06-01` converting to UTC time.

**Comment by kennethmyhra** [comment]
For your last question you need to specify the time zone on the query string.

If you look in the documentation for the [date](http://hl7.org/fhir/search.html#date) search parameter type it says that: `you SHOULD provide a time zone if the time part is present.`

**Comment by whyfate** [comment]
@kennethmyhra  You mean my query conditions should be written like this
```json
GET /fhir/Schedule?date=ge2021-06-01+08:00
```

**Comment by kennethmyhra** [comment]
First I will need to construct the Schedule resource like this:
```
{
    "resourceType": "Schedule",
    "planningHorizon": {
        "start": "2021-06-01T00:00:00+08:00",
        "end": "2021-06-01T08:00:00+08:00"
    },
    "actor": [{ 
            "reference": "Practitioner/28",
            "display": "Vera Valve"
        }]
}
```
Then when I query for resources within that timeframe I would need to specify the time part and time zone:
```
GET fhir/Schedule?date=ge2021-06-01T00:00:00+08:00
```

I created the resource in the public test server. You can try this query against it: https://spark.incendi.no/fhir/Schedule?_format=json&date=ge2021-06-01T00:00:00+08:00

**Comment by kennethmyhra** [comment]
For your first part I just looked at a fix which I think should solve the `less than or equal` issue

**Comment by whyfate** [comment]
In the [fhir search doc](http://www.hl7fhir.cn/R4/search.html#date),


[parameter]=eq2013-01-14 | 2013-01-14T00:00 matches <br/>2013-01-14T10:00 matches
-- | --


we don't support this `ge2021-06-01+08:00`?

**Comment by kennethmyhra** [comment]
I see no way of specifying time zone on just a date value. So that query is not going to work

This query though solves the issue of querying within a day (if you need to use a time zone other than UTC):
```
GET Schedule?date=ge2021-06-01T00:00:00+08:00&date=lt2021-06-02T00:00:00+08:00
```

Another way to solve this is to always post UTC dates to the server and handle the time zones client-side, then the query you have above will work with Spark. Dates and time zones is a hard nut to crack, and there isn't an easy answer to the problems you can and will encounter.

**Comment by whyfate** [comment]
Yes, I'm using what you said, but there may be a gap with the standard.

**Comment by whyfate** [comment]
When my colleagues use the `date` to query, they will look at the `fhir doc` and ask why they don't support the query on docs.

**Comment by kennethmyhra** [comment]
I disagree with there being a gap, time zones are a difficult area as you see from the "there be dragons" section on the page you linked to:
```
Managing time zones and offsets and their impact on search is a very difficult area.
The FHIR implementation community is still investigating and debating the best way to handle time zones.
```

It also states that: `Implementation guides may make additional rules in this regard.`

Such a rule could be the rule I stated above, by always using using UTC when communicating with the server, that is also what I would recommend.

Another way is that you fix your server at your local time zone, but I would not recommend that I have seen a few pitfalls in projects doing that.

**Comment by whyfate** [comment]
So when we write data, we should add the time zone.
Use `DateTimeOffset` instead of `DateTime` whenever possible

**Comment by kennethmyhra** [comment]
Yes, when you create new resources or update existing ones you need to be aware of the time zone and specify that. When you query the server you need to specify the time zone as well

DateTimeOffset would be the recommended type to use.

**Comment by whyfate** [comment]
I got it,Thinks.
