### ISSUE TITLE
Concurrent Search Bug

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#393]
**Describe the bug**
Such as the title

**To Reproduce**
it's my test code
```csharp
static void ConcurrentSearchTest()
{
    var client = new FhirClient("https://spark.incendi.no/fhir");
    // This request will return two resource: Encounter and Patient
    var hasResourceURL = "https://spark.incendi.no/fhir/Encounter?_id=2&_include=Encounter:subject";
    // This request has no resource returned
    var noResourceURL = "https://spark.incendi.no/fhir/Encounter?_id=22222222&_include=Encounter:subject";
    for (int i = 0; i < 500; i++)
    {
        var j = i;
        System.Threading.Tasks.Task.Run(async () =>
        {
            if (j % 2 == 0)
            {
                var bundle = (Bundle)await client.GetAsync(hasResourceURL);
                if (bundle.Entry.Count != 2)
                {
                    Console.WriteLine($"{j}---search has resource error");
                }
                else
                {
                    Console.WriteLine($"{j}---succeed");
                }
            }
            else
            {
                var bundle = (Bundle)await client.GetAsync(noResourceURL);
                if (bundle.Entry.Count > 0)
                {
                    Console.WriteLine($"{j}---search no resource error");
                }
                else
                {
                    Console.WriteLine($"{j}---success");
                }
            }
        });
    }
}
```

**Expected behavior**
all print {j}---success

**Screenshots**

![image](https://user-images.githubusercontent.com/13515020/121625081-589c8780-caa5-11eb-921c-950aafec327f.png)

**Comment by whyfate** [comment]
I debugged the source code and found that the cause of the error was the concurrency problem in the  `SnapshotPaginationProvider` 
https://github.com/FirelyTeam/spark/blob/6ac316e456848f35bc2427a3d27556a272c9f183/src/Spark.Engine/Service/FhirServiceExtensions/SnapshotPaginationProvider.cs#L15-L35
the Call chain is:
`AsyncFhirService` -> `PagingService` -> `SnapshotPaginationProvider`
Although `SnapshotPaginationProvider` is injected `Transient`, because `AsyncFhirService` is a `Singleton`, `SnapshotPaginationProvider` is also a `Singleton`.
https://github.com/FirelyTeam/spark/blob/212d071003bc1a57affe7aaceacef133108a9b00/src/Spark.Engine/Service/AsyncFhirService.cs#L370-L390

At present, I have changed `AsyncFhirService` to `Transient` to solve the problem temporarily, but I don't think this is the best way.Maybe need to refactor `FhirService`.

**Comment by kennethmyhra** [comment]
It was singleton in good old classic Spark (.NET FW), and probably therefore it is singleton in the .NET Core/Standard version of Spark. Actually I do not see a good reason for `AsyncFhirService` to be a singleton and I think we should consider making it transient instead.

**Comment by whyfate** [comment]
But creating an `AsyncFhirService` is time consuming.
https://github.com/FirelyTeam/spark/blob/212d071003bc1a57affe7aaceacef133108a9b00/src/Spark.Engine/Service/AsyncFhirService.cs#L28-L43
This has a effect on Performance.

**Comment by kennethmyhra** [comment]
Yes, that is a concern. I have not measured the effect it would have on performance, but yes that would be the concern.

**Comment by one0410** [comment]
Hi,
I have the same problem. 
If I query API at almost the same time, sometimes I got weird response different from what I expected.
So that I couldn't put this project into a production environment.


For example, I have 20 Device resource in DB.
If I query identifier 000000000001, I expect a result with same identifier.
Please see the following code, sometimes I got a random result.
Please help.

```javascript
  testFhir(): void {
    for (let i = 0; i <20; i++) {
      this.http.get('https://esp32fhir.azurewebsites.net/fhir/Device?identifier=' + i.toString().padStart(12, '0'))
      .toPromise()
      .then((res: any) => {
        console.log(i, res.entry[0].resource);
      });
    }
  }
```
![image](https://user-images.githubusercontent.com/11656628/124883524-fd0ddd00-e003-11eb-9cb2-62f6abc28cdf.png)

Andy

**Comment by one0410** [comment]
Hi @whyfate,

Could you tell me how you changed AsyncFhirService to Transient to solve the problem temporarily ?

Andy

**Comment by whyfate** [comment]
@one0410  I modified the source code.
https://github.com/FirelyTeam/spark/blob/e130c88d83a462d82f2fae3bb127146ccffe7d2a/src/Spark.Engine/Extensions/NetCore/IServiceCollectionExtensions.cs#L85
```csharp
services.TryAddTransient<IAsyncFhirService, AsyncFhirService>();
```

**Comment by kennethmyhra** [comment]
@whyfate  how did that affect the performance?

**Comment by one0410** [comment]
@whyfate You are right, the performance is terrible.
@kennethmyhra Is this what you want ?

singleton:
![image](https://user-images.githubusercontent.com/11656628/124896518-187ee500-e010-11eb-93cc-477699edeb22.png)

transient:
![image](https://user-images.githubusercontent.com/11656628/124896269-deadde80-e00f-11eb-8052-9578d2f38269.png)

**Comment by kennethmyhra** [comment]
@one0410, absolutely not. I haven't yet had time to look into the root cause of this. If any of you have time to do that it would be much appreciated. Anyways, I'll put it into the current sprint for the next release

**Comment by whyfate** [comment]
I have an immature suggestion, which is to pass `snapshot` into the parameter of this method.
https://github.com/FirelyTeam/spark/blob/e130c88d83a462d82f2fae3bb127146ccffe7d2a/src/Spark.Engine/Service/FhirServiceExtensions/ISnapshotPagination.cs#L19
```csharp
Bundle GetPage(Snapshot snapshot,int? index = null, Action<Entry> transformElement = null); 
```
Replacing `SnapshotPaginationProvider` internal variables `_snapshot` with parameters
https://github.com/FirelyTeam/spark/blob/e130c88d83a462d82f2fae3bb127146ccffe7d2a/src/Spark.Engine/Service/FhirServiceExtensions/SnapshotPaginationProvider.cs#L29-L58
But emmm...bad code warning!!!

**Comment by kennethmyhra** [comment]
I've done some research and can confirm that I am seeing the error as well. I tried putting a SemaphoreSlim around the code in AsyncFhirService.SearchAsync (as a hot fix), it helps, but it slows it down since it forces the requests to run synchronously one-by-one.

I need to try and reproduce this with FhirServiceService to see if we had this problem before we added AsyncFhirService

**Comment by whyfate** [comment]
This problem is `Snapshot` design, which has existed for a long time, not async.

**Comment by kennethmyhra** [comment]
This is fixed in both STU3 and R4. If you are compiling from source, please verify by pulling. If you are using the NuGet packages I will create a new release today
STU3 - https://www.nuget.org/packages/Spark.Engine.STU3
R4 - https://www.nuget.org/packages/Spark.Engine.R4

Summarized I split ISnapshotPaginationProvider and ISnapshotPagination into two implementations making sure as @whyfate pointed out that Snapshot is not affected by the singleton behavior of ISnapshotPaginationProvider. There is a more lengthy explanation in the commit/PR

**Comment by one0410** [comment]
Thank you very much. This does help me a lot. You are really amazing.

**Comment by whyfate** [comment]
@kennethmyhra Hi,I saw your implementation,I don't think it's good to directly a new `SnapshotPaginationService`.
How about this?
```csharp
services.AddTransient<ISnapshotPaginationProvider, SnapshotPaginationProvider>();
```
```csharp
public class PagingService : IPagingService
{
    private readonly ISnapshotStore _snapshotstore;
    private readonly IServiceProvider _serviceProvider;

    public PagingService(ISnapshotStore snapshotstore, IServiceProvider serviceProvider)
    {
        _snapshotstore = snapshotstore;
        _serviceProvider = serviceProvider;
    }

    public ISnapshotPagination StartPagination(Snapshot snapshot)
    {
        return Task.Run(() => StartPaginationAsync(snapshot)).GetAwaiter().GetResult();
    }

    public ISnapshotPagination StartPagination(string snapshotkey)
    {
        return Task.Run(() => StartPaginationAsync(snapshotkey)).GetAwaiter().GetResult();
    }

    public async Task<ISnapshotPagination> StartPaginationAsync(Snapshot snapshot)
    {
        if (_snapshotstore != null)
        {
            await _snapshotstore.AddSnapshotAsync(snapshot).ConfigureAwait(false);
        }
        else
        {
            snapshot.Id = null;
        }

        var snapshotPaginationProvider = _serviceProvider.GetRequiredService<ISnapshotPaginationProvider>();
        return snapshotPaginationProvider.StartPagination(snapshot);
    }
    public async Task<ISnapshotPagination> StartPaginationAsync(string snapshotkey)
    {
        if (_snapshotstore == null)
        {
            throw new NotSupportedException("Stateful pagination is not currently supported.");
        }

        var snapshotPaginationProvider = _serviceProvider.GetRequiredService<ISnapshotPaginationProvider>();
        return snapshotPaginationProvider.StartPagination(await _snapshotstore.GetSnapshotAsync(snapshotkey).ConfigureAwait(false));
    }
}
```

**Comment by kennethmyhra** [comment]
@whyfate the plan is to do this in the next version. While I agree with you - right now the only downside is that you can't make your own implementation of the interface `ISnapshotPagination` which was the interface touched in this iteration

I also see now that you are referring to some other interface (`IPagingService`) and implementation (`PagingService`) which was not touched in this iteration. The whole infrastructure around snapshot pagination seems messy and unfinished which I also noticed when I started touching this part and therefore did not put too much effort into the infrastructure part at this point

**Comment by whyfate** [comment]
I see,thanks.
