### ISSUE TITLE
Make ICapabilityStatementService reusable 

### ISSUE THREAD

**Issue by svdberg-convenient** [FirelyTeam/spark#394]
**Is your feature request related to a problem? Please describe.**
I'm doing a project for work based on Spark, with a custom data store. We only need to support a subset of FHIR resources and actions on those resources

The contents of the Capability-statement should reflect the resources (and interactions on those resources) we support., though

What I planned to do was:
* Remove the default `ICapabilityStatementService` implementations from the list of services. 
* Introduce my own implementation of the interface and add that one to the list, 
* Reuse `CapabilityStatementBuilder` to fill our own statement. 

This all fell apart because  ICapabilityStatementService` is marked as internal. 

**Describe the solution you'd like**

I think marking `ICapabilityStatementService` as public should be enough to make what I described earlier feasible. All the other parts needed are already there. 

**Describe alternatives you've considered**

I considered copying parts of  `AsyncFhirController` to our application code. This duplicates functionality that's already present i n Spark though, which is not ideal.

**Comment by kennethmyhra** [comment]
Hey @svdberg-convenient, I agree it should be marked as public. I have created a PR #395 and can merge that pretty quickly. Are you using the NuGet packages? If so I will need to create a new release

**Comment by kennethmyhra** [comment]
Just published a new release v1.5.6 with a fix for this. The NuGet package is available here: https://www.nuget.org/packages/Spark.Engine.R4/

**Comment by svdberg-convenient** [comment]
@kennethmyhra, that was fast. Thanks!

Yeah, I'm using the NuGet packages.
