### ISSUE TITLE
Question regarding delete + insert versus update (w/ upsert)

### ISSUE THREAD

**Issue by phrederick** [FirelyTeam/spark#398]
https://github.com/FirelyTeam/spark/blob/76c6499806e9986ac0d12309d7d7491224049e89/src/Spark.Mongo/Search/Infrastructure/MongoIndexStore.cs#L59

Hi all!
I am curious about this comment in the code which looks to have been in place for quite some time. I am just about to implement this very suggestion in our project to resolve an issue we occasionally see where duplicate searchindexes can be created, but I am a little bit nervous about it given that you guys haven't done it too.

Is it just a matter of "if it ain't broke, don't fix it" in your case?

**Comment by kennethmyhra** [comment]
Hey @phrederick That is as you state a matter of "if it ain't broke, don't fix it." When we do refactoring of these parts we will reconsider the way we use the API, but then from the current knowledge and mindset.

In the near future I will probably go through some of these comments and remove them if there isn't any current bugs that are affected by them.

**Comment by phrederick** [comment]
@kennethmyhra thanks mate -- appreciate the response. It puts my mind somewhat at ease knowing there was no sinister reason behind the long-standing comment :)

Feel free to close this one if you want.

**Comment by kennethmyhra** [comment]
I notice that you mention duplicate search indexes. That is an issue that I am not aware of. Is that a problem that you are frequently experiencing, and when that occurs how does that affect Spark?

**Comment by phrederick** [comment]
@kennethmyhra - it doesn't happen often, but it's often enough to cause problems for us because in our case we end up with a single current (i.e. not superseded) record in our 'resources' collection but two 'searchindex' records where one is pointing to the superseded record.

Our updates can come in **very rapidly** sometimes which is not ideal but not something we can easily fix at the moment. My suspicion on the issue is as follows: As the updates come in, in a perfect world the code should execute like this:

update 1 Remove()
update 1 Insert()
update 2 Remove()
update 2 Insert()

In reality, I think there are instances where this happens (and this might be unique to our infrastructure / setup):

update 1 Remove()
update 2 Remove()
update 1 Insert()
update 2 Insert()

**Comment by kennethmyhra** [comment]
@phrederick I think we should create a bug for this. I haven't had the time to do any research on this. Do you by any chance have the possibility to test out the change you proposed?

**Comment by phrederick** [comment]
@kennethmyhra I'll move the convo over to the bug you've created 👍
