### ISSUE TITLE
Spark.Store Transaction Commit Fails Leaving Resource in 'queued' status

### ISSUE THREAD

**Issue by geronimovillarreal** [FirelyTeam/spark#41]
When creating, updating or deleting a Resource document, the result of commiting the transaction is not evaluated for failure. When the sweep() function is called to move the Resource document from 'queued' to 'current' the collection save result is not evaluated.  When this fails no exception is raised and the transaction is not rolled back leaving the Resource document in the state of 'queued'.

![image](https://cloud.githubusercontent.com/assets/13771820/9237379/25fec984-4110-11e5-8c07-95a338b490b1.png)

![image](https://cloud.githubusercontent.com/assets/13771820/9237436/70789a76-4110-11e5-8e91-59133d4cc3cb.png)

Proposed fix is to evaluate the result of Transaction.cs line 144 to ensure the Update was successful and the documents affected is equal to 1.  If this evaluation fails, the sweep() mehod will throw an exception with the details of the failure so that the transaction fails and the Rollback() method is called.

**Comment by kennethmyhra** [comment]
Closing this, these methods are no longer used
