### ISSUE TITLE
Impossible to post a Bundle using a Json payload

### ISSUE THREAD

**Issue by JeanRessouche** [FirelyTeam/spark#414]
**Describe the bug**
Impossible to post a Bundle using a [Json payload](https://www.hl7.org/fhir/message-request-link.json.html).

```
{
  "errors": {
    "entry[0].resource.resourceType.resource": [
      "Could not create an instance of type Hl7.Fhir.Model.Resource. Type is an interface or abstract class and cannot be instantiated. Path 'entry[0].resource.resourceType', line 10, position 23."
    ],
    "entry[1].resource.resourceType.resource": [
      "Could not create an instance of type Hl7.Fhir.Model.Resource. Type is an interface or abstract class and cannot be instantiated. Path 'entry[1].resource.resourceType', line 39, position 23."
    ],
    "entry[2].resource.resourceType.resource": [
      "Could not create an instance of type Hl7.Fhir.Model.Resource. Type is an interface or abstract class and cannot be instantiated. Path 'entry[2].resource.resourceType', line 98, position 23."
    ]
  },
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-02ea670a47d5b54183606ff059d91057-0f5e5dbc0b87ad49-00"
}
```

**To Reproduce**
1. Create a controller endpoint that accept in the body a Bundle. The ${operation} controller is a good candidate.
2. Post a json bundle, with header Content-Type application/fhir+json or application/json

**Expected behavior**
Accepted request, entering the endpoint

**Additional context**
Seems to be working fine with [Xml payload](https://www.hl7.org/fhir/message-response-link.xml.html).

**Comment by kennethmyhra** [comment]
Hi @souchprod could you show me the exact endpoint you are calling, the exact url you are posting against

Also, are you running the Spark.Web project or have you used the NuGet packages and created your own controller? If the latter please also post the code for the endpoint

**Comment by JeanRessouche** [comment]
Hello Kenneth, thanks for your answer.

I am using the NuGet package.
Here is a minimal version, to implement the /$process-message POST endpoint.

```c#
        [HttpPost("${operation}")]
        public FhirResponse ServerOperation([FromRoute] string operation, [FromBody] Bundle bundle = null, [FromQuery] bool async = false, [FromQuery(Name = "response-url")]  string responseUrl = null)
        {
            switch (operation.ToLower())
            {
                case "process-message":
                {
                    return Respond.WithBundle(bundle);
                }
                case "error": throw new Exception("This error is for testing purposes");
                default: return Respond.WithError(HttpStatusCode.NotFound, "Unknown operation");
            }
        }
```

**Comment by kennethmyhra** [comment]
@souchprod This is because the internal MVC formatters `SystemTextJsonInputFormatter` and `SystemTextJsonOutputFormatter` is interfering. I forgot to update the [spark-example](https://github.com/incendilabs/spark-example) accordingly when upgrading from .net core 2.x to 3.1

If you apply the same changes I did in this commit it should fix your issue: https://github.com/incendilabs/spark-example/commit/b1bb24a0d58519a5bc196dafd81681d90ac2e36b

Should probably consider to move this into the AddFhir method to avoid any confusion in the future

**Comment by JeanRessouche** [comment]
Thanks ! I will try it

**Comment by JeanRessouche** [comment]
Working, in my case, under .net 5.0 & with NewtonSoft i had to remove those:

```
options.InputFormatters.RemoveType<NewtonsoftJsonInputFormatter>();
options.OutputFormatters.RemoveType<NewtonsoftJsonOutputFormatter>();
```
