### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jaime-olivares** [FirelyTeam/spark#45]
Any plans to implement this product into Linux by using the new VS 2015 tools?
MongoDB supports Mono 3.x, so it is feasible.

**Comment by mbaltus** [comment]
There are no plans to do this right now, although we are thinking about changing to ASP 5, MCV 6 and the dotnet core. I'll put this question on hold for now.

**Comment by tutukar** [comment]
Any movement on this front? Is this still something you are looking to do?

**Comment by cknaap** [comment]
Update: We intend to have at least a beta version of Spark on .Net Core by the end of the year (2016). And it will probably not be just a port of the current codebase, but instead in a structure leveraging the benefits that (ASP).Net Core brings us.

**Comment by tutukar** [comment]
Does this mean a beta version on .net core by end of the year is not expected and the time line around it is unknown?
