### ISSUE TITLE
'Spark.sln' file link mistake

### ISSUE THREAD

**Issue by dreamofsnail** [FirelyTeam/spark#456]
**Describe the bug**
A simple mistake
Real filesystem: .docker/linux/r4.archive.gz
'Spark.sln': .docker\linux\dstu2.archive.gz

**Screenshots**
![image](https://user-images.githubusercontent.com/4602134/153310499-977306de-4d56-4bf8-90e9-cfc70c83bcb2.png)

![image](https://user-images.githubusercontent.com/4602134/153310545-a4537e56-b4c1-4838-9290-a28eb5e611fc.png)

**Comment by kennethmyhra** [comment]
Thanks for noticing! Should be fixed now
