### ISSUE TITLE
Audit / log mechanism?

### ISSUE THREAD

**Issue by jaime-olivares** [FirelyTeam/spark#48]
Does this platform contains or supports an extension mechanism for logging or auditing?
I mean the product, not the FHIR standard.
I would like to register all the activity related to all ingoing and outgoing messages.

**Comment by ewoutkramer** [comment]
Hi Jaime, what other have done is use the OnBeforeRequest and OnAfterResponse events on the FhirClient. These give you access to the http request just before it is sent and just after you have received a response, you can use these to debug!   As well, you can use tools like Fiddler to intercept requests and responses and debug your session.

**Comment by jaime-olivares** [comment]
Hi Ewout, the proposed client-side solution doesn't seem adequate for audit. The control of the mechanism shall be out of the client scope for security reasons. Moreover, if there are several applications accessing a FHIR repository and one of them do not or can not record an activity, there is no way an audit application can guess that an operation was done.
Other aspect is performance: if the audit is triggered at client side, it will produce an additional client-server traffic, while the typical server-side operation would spare that.

**Comment by ewoutkramer** [comment]
Sorry, Jaime, I am also maintaining the .NET client issues, and was thinking on the wrong side of the wire ;-)

**Comment by jaime-olivares** [comment]
Hi Ewout, thanks for keeping alive this suggestion. Is there anything done or planned?

**Comment by mbaltus** [comment]
Event logging has been planned in our roadmap for the coming month.

**Comment by mharthoorn** [comment]
Some logging was implemented this year. Let's check how far this issue is now resolved.
