### ISSUE TITLE
POST to /Binary with non-FHIR Content-Type yield HTTP 415 Unsupported Media Type

### ISSUE THREAD

**Issue by JeremiahSanders** [FirelyTeam/spark#509]
# Symptom

## Environment

Using `Spark.Engine.R4` NuGet package (version `1.5.14`) in a .NET 6 API with a `FhirController` matching the [reference implementation](https://github.com/FirelyTeam/spark/blob/209a49aa27608b45ec0f30092eaece474ea2a98a/src/Spark.Web/Controllers/FhirController.cs).

## Action

Request is submitted to `POST ${fhirServerUrl}/Binary` with raw, non-FHIR content (e.g., `application/pdf`).

## Result

Request is rejected with HTTP status code `415 Unsupported Media Type`.

## Expected

A `Binary` FHIR resource should be created (and `201 Created` returned).

# Cause

The `Spark.Engine.Handlers.NetCore.FormatTypeHandler` uses `Spark.Engine.Extensions.HttpRequestFhirExtensions.IsRawBinaryPostOrPutRequest()` to determine if the request is creating a `Binary` resource. (Good so far.)

The problem arises when `IsRawBinaryPostOrPutRequest()` attempts to get the request URI, from `Spark.Engine.Extensions.HttpRequestFhirExtensions.GetRequestUri()`. In [`Spark.Engine.Extensions.HttpRequestFhirExtensions#L63`](https://github.com/FirelyTeam/spark/blob/209a49aa27608b45ec0f30092eaece474ea2a98a/src/Spark.Engine/Extensions/HttpRequestFhirExtensions.cs#L63) the `httpRequestFeature.RawTarget` is used to reconstruct the request path.

The `httpRequestFeature.RawTarget` is set to the application root (`/`); however, `httpRequestFeature.Path` contains `/Binary`.

As a result, the _reconstructed_ request path fails to contain `"Binary"` when tested (in [`Spark.Engine.Extensions.HttpRequestFhirExtensions.IsRawBinaryPostOrPutRequest()`](https://github.com/FirelyTeam/spark/blob/209a49aa27608b45ec0f30092eaece474ea2a98a/src/Spark.Engine/Extensions/HttpRequestFhirExtensions.cs#L165).

# Additional Testing Notes

The explanation above was tested to be the root cause by referencing `Spark.Engine` via local project reference (cloned from current `master/r4`). In the test, [`Spark.Engine.Extensions.HttpRequestFhirExtensions#L63`](https://github.com/FirelyTeam/spark/blob/209a49aa27608b45ec0f30092eaece474ea2a98a/src/Spark.Engine/Extensions/HttpRequestFhirExtensions.cs#L63) was updated. That single change caused the request to process as expected, and the server returned the original content (as expected).

## Current (returns `HTTP 415` when attempting to `POST /Binary` with non-FHIR content)

```csharp
return $"{request.Scheme}://{request.Host}{httpRequestFeature.RawTarget}";
```

## Corrected (new, tested-functional version)

```csharp
return $"{request.Scheme}://{request.Host}{httpRequestFeature.Path}";
```

**Comment by kennethmyhra** [comment]
Hey @JeremiahSanders,

I am not really able to recreate the issue you are seeing here. See the valeues of the mentioned properties in my picture below. However I do believe it is more proper to use HttpRequestFeature.Path which you are suggesting so I will update accordingly

![image](https://user-images.githubusercontent.com/248795/195667041-c837d6cc-c3ae-4819-aa51-d030cfe643d4.png)
