### ISSUE TITLE
FILE UPLOAD ISSUE

### ISSUE THREAD

**Issue by LumiProj** [FirelyTeam/spark#523]
Hi,

I am using this project in my current healthcare exchange, everything is working fine except I am facing issue when I add File Upload functionality. I am getting following error. Please guys help me out to resolve this critical problem.
**{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "diagnostics": "Unsupported Media Type"
        }
    ]
}**

**Comment by kennethmyhra** [comment]
I need more information regarding how you do file upload. POSTing Binaries to Spark has been tested and should work.

**Comment by LumiProj** [comment]
Hi,
Thank you for your prompt response.I am using the latest of Spark version 1.5.14 and .Net core version 6.0 
I have a simple controller to upload files using the [FromForm] attribute as shown below.
[HttpPost, DisableRequestSizeLimit] 
        public async Task<ApiResponse<Document>> UploadFile
( [FromForm] IFormFile formFile )
        {
          
            // Removed my code
            return null;
       
        }
Postman CURL script to use this method is.
curl --location --request POST 'https://localhost:44364/api/Document' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1NzYzZWQyYjQ0MGI0OTk4OWJlNGY1NjQyNGVkYzFlYiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJqYW1pbGFrMjJAeWFob28uY29tIiwiZXhwIjoxODIyNzE3NzA5LCJpc3MiOiJYZWxsZSIsImF1ZCI6IlhlbGxlIn0.acSOpS1LHJSzgFxJXoQBnYAMicLSsNzWJZQBLeKR4s4' \
--header 'Content-Type: multipart/form-data' \
--form 'File=@"/F:/DCIM/105APPLE/IMG_5008.JPG"' \
--form 'CreatedBy="9b12d575-a29a-436d-8677-c88997327a4f"' \
--form 'DocumentType="Workbook"'

but when I submit the form I am getting an unsupported media type error.
I hope you got my issue, please help me out.
Thanks

**Comment by kennethmyhra** [comment]
The code you are sharing do not have any relevance to FHIR APIs so I suspect there is some lack of understanding on how to interact with FHIR APIs

You can try the following `curl` command against my official test server. Create a text file called `test.txt` with some random content and run the following command:
```sh
curl --request POST --data-binary "@test.txt" https://spark.incendi.no/fhir/Binary
```

I recommend that you take a look at the examples I've put up, like this one: https://github.com/incendilabs/spark-example

**Comment by LumiProj** [comment]
Hi,

Thank you again for the prompt response. Well I know there is a Binary resource where we can store all sorts of documents in binary format which is perfectly fine and it is working at my end as well, I don't have issues with it.

My client wanted to store all their documents in Mongo GridFS, For that purpose I created a separate controller to store and retrieve Documents in GridFS. 

For more information I can share my complete project so you would have a clear understanding of my problem and it would help you help me out to resolve this issue.

Here is the complete project, please fill the MongoDB connection string inside appsettings.json.
https://github.com/lumisoftllc/MongoFhir

Below is the curl script to upload files in GridFS.

curl --location --request POST 'https://localhost:44364/api/Document' \
--form 'File=@"/F:/DCIM/105APPLE/IMG_5008.JPG"' \
--form 'CreatedBy="9b12d575-a29a-436d-8677-c88997327a4f"' \
--form 'DocumentType="Workbook"'

Thanks

**Comment by LumiProj** [comment]
Hi,

Please guys I am wailing for the response.

**Comment by kennethmyhra** [comment]
We are overriding the formatters in the MVC pipeline which then interferes with your API at `api/Document`. The easiest way to get this to work is to move your DocumentController into a separate project. Then you will have one endpoint (project 1) which is pure FHIR APIs and another endpoint (project 2) where you can add your own APIs like the DocumentController API.

**Comment by LumiProj** [comment]
Hi!

Thank you so much for the prompt response.  

Well my task is to use the same end point for both Fhir and other custom controllers.
Anyhow I have achieved this behavior by sending the files in base64 and then converting into stream and store in GridFS.
Despite that, I appreciate your team for working on this amazing project.

**Comment by kennethmyhra** [comment]
Thanks for saying that @LumiProj, that's appreciated
