### ISSUE TITLE
Provenance searches return 0 results when using FHIR R4 'patient' parameter

### ISSUE THREAD

**Issue by JeremiahSanders** [FirelyTeam/spark#526]
**Describe the bug**
Searches for `Provenance` resources using its [`patient` parameter](https://www.hl7.org/fhir/provenance.html#search) return `0` results. Searches for the same target resource using the [`target` parameter](https://www.hl7.org/fhir/provenance.html#search) return resources which are an exact match.

**To Reproduce**

The following code reproduces the issue using the reference server:

```csharp
Uri baseUri = new Uri("https://spark.incendi.no/fhir", UriKind.Absolute);
var settings = new FhirClientSettings
{
	VerifyFhirVersion = false,
	PreferredReturn = Prefer.ReturnRepresentation,
	PreferredFormat = ResourceFormat.Json
};
var fhirClient = new FhirClient(baseUri, settings);

// Retrieve an example patient to reference
var patients = await fhirClient.SearchAsync<Patient>();
var firstPatient = patients.GetResources().OfType<Patient>().First();
var resourceIdentity = firstPatient.ResourceIdentity();
var resourceIdentityWithoutVersion = ResourceIdentity.Build(firstPatient.TypeName, firstPatient.Id);

// Create Provenance resources
DateTimeOffset recorded = System.DateTime.UtcNow;
var agent = new Provenance.AgentComponent
{
	Role = new List<Hl7.Fhir.Model.CodeableConcept> { new CodeableConcept("http://terminology.hl7.org/CodeSystem/v3-ParticipationType", "AUT") },
	Who = new ResourceReference(resourceIdentityWithoutVersion.ToString())
};
var withVersionResponse = await fhirClient.CreateAsync(new Provenance
{
	Target = new List<Hl7.Fhir.Model.ResourceReference>{
		new ResourceReference{
			Type = firstPatient.TypeName,
			Reference = resourceIdentity.ToString()
		}
	},
	Recorded = recorded,
	Agent = new List<Hl7.Fhir.Model.Provenance.AgentComponent> { agent }
});
var withoutVersionResponse = await fhirClient.CreateAsync(new Provenance
{
	Target = new List<Hl7.Fhir.Model.ResourceReference>{
		new ResourceReference{
			Type = firstPatient.TypeName,
			Reference = resourceIdentityWithoutVersion.ToString()
		}
	},
	Recorded = recorded,
	Agent = new List<Hl7.Fhir.Model.Provenance.AgentComponent> { agent }
});


// Search
//   See: https://www.hl7.org/fhir/provenance.html#search
//   See: https://www.hl7.org/fhir/search.html#versions
// Search by Target - Each of these return 1 result
var searchByVersionedTarget = await fhirClient.SearchUsingPostAsync<Provenance>(new SearchParams("target", resourceIdentity.ToString()));
var searchByUnversionedTarget = await fhirClient.SearchUsingPostAsync<Provenance>(new SearchParams("target", resourceIdentityWithoutVersion.ToString()));
// Search by Patient - These return 0 results
var searchByVersionedPatient = await fhirClient.SearchUsingPostAsync<Provenance>(new SearchParams("patient", resourceIdentity.ToString()));
var searchByUnversionedPatient = await fhirClient.SearchUsingPostAsync<Provenance>(new SearchParams("patient", resourceIdentityWithoutVersion.ToString()));

// Cleanup
await fhirClient.DeleteAsync(withVersionResponse);
await fhirClient.DeleteAsync(withoutVersionResponse);
```

**Expected behavior**

When the `Provenance`'s `target` is a `Patient`, searching by `target` and `patient` should return the same results.

**Spark version**
  - Version: `1.5.14`

**Operating system + Database**
  - OS: Linux and Windows
  - Database: MongoDB

**Container service / Cloud infrastructure:**
  - Container service: AWS Elastic Container Service (and whatever https://spark.incendi.no/fhir uses)
  - Cloud provider: AWS (and whatever https://spark.incendi.no/fhir uses)
  - Cloud infrastructure: VM (and whatever https://spark.incendi.no/fhir uses)
  - Database as a service: AWS DocumentDB w/ MongoDB API  (and whatever https://spark.incendi.no/fhir uses)
  
**Additional context**
May also relate to #521 and #522.

**Comment by kennethmyhra** [comment]
Thanks for reporting @JeremiahSanders and sorry for not coming back to you on the other issues you have reported.

There is a known issue for some reference searches like the one you are reporting here. I will have to dig up the details on what our findings where back then.

**Comment by JeremiahSanders** [comment]
Thanks, @kennethmyhra !

If I've erred in executing those searches or arranging the test cases, please let me know. I'll happily retest.
