### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by LumiProj** [FirelyTeam/spark#529]
**Describe the bug**

Hi! I wanted to search for a patient from its gender. As per Fhir search documentation I am using the following pattern, but the issue is it is not working even on the beta site of this project. I am trying to search only MALE patients but as a result I am receiving all the patients.
https://spark.incendi.no/fhir/Patient?patient.gender=male
 
Please guys help me out. I am already using this library in my production environment. Everything is going well except the searching. 

**Spark version**
  - Version: [e.g. 1.5.14]

**Operating system + Database**
  - OS: [e.g. Windows]
  - Database: [e.g. MongoDB]

**Container service / Cloud infrastructure:** 
  - Cloud infrastructure: [Asp.net Core]
  - Database as a service: [e.g. CosmosDB w/ MongoDB API]

**Comment by kennethmyhra** [comment]
You are not supposed to prefix the search parameter with patient in this context.
```
https://spark.incendi.no/fhir/Patient?gender=male
```
https://spark.incendi.no/fhir/Patient?gender=male&_format=json
