### ISSUE TITLE
Snapshot is not working

### ISSUE THREAD

**Issue by LumiProj** [FirelyTeam/spark#530]
**Describe the bug**
Hi. I have tested the hosted fhir server of Spark. Everything is working. I can Query History , Snapshots everything, but History and Snapshots are not working at my end.
I am following the given Asp.net Core sample project https://github.com/incendilabs/spark-example, Clone on my machine changes the mongodb connection string. I am able to create , update resources but if I query snapshots nothing is working.
I am receiving a connection refused error.

https://localhost:5001/fhir/_snapshot?id=3d76f8a1-f346-4fb9-98e8-c731f65fafed&_offset=6540
 
**Expected behavior**
Query should work and return Bundle like we are getting from this URL.
https://spark.incendi.no/fhir/_snapshot?id=3d76f8a1-f346-4fb9-98e8-c731f65fafed&_offset=6540

 
**Spark version**
  - Version: 1.5.14.0

**Operating system + Database**
  - OS: Windows
  - Database: MongoDB

**Comment by kennethmyhra** [comment]
The spark-example is fairly simple as it stands, you will have to add the `_snapshot` and `_history` endpoints to your controller.

`_snapshot` implementation: https://github.com/FirelyTeam/spark/blob/9455876535df06a8deec60761a0d6d02a6d87efc/src/Spark.Web/Controllers/FhirController.cs#L186-#L192

`_history` implementation: https://github.com/FirelyTeam/spark/blob/9455876535df06a8deec60761a0d6d02a6d87efc/src/Spark.Web/Controllers/FhirController.cs#L179-#L184

**Comment by LumiProj** [comment]
Thanks and I highly appreciate it.
