### ISSUE TITLE
How to implement extensions 

### ISSUE THREAD

**Issue by mikolaj-jankowski** [FirelyTeam/spark#533]
Hi,
What should I implement in order to save a resource with custom nested extensions and also be abo to retrieve that resource via Search endpoint?

I have noticed that resources are stored in resources collection in db with all extensions however extensions are missing in the searchIndex collection.

**Comment by kennethmyhra** [comment]
To answer your original question.

To make a FHIR extension searchable you will have to add a search parameter for the FHIR extension. You will have to use the extension method `AddCustomSearchParameters` on `IServiceCollection`.

You can read more about search parameters here: http://hl7.org/fhir/searchparameter.html

**Comment by mikolaj-jankowski** [comment]
@kennethmyhra thanks. 
I have found the answer here https://github.com/FirelyTeam/spark/discussions/516 and decided to remove my question.
Because you replied anyway I will restore my original question.

As you said I can add custom SearchParameters inside middleware - that's fine and no doubt how to do it.
I also would like to allow users to make a POST SearchParams through the API and then use them. 
Should I implement a pice of code where I get these objects from db and attach them dynamically in runtime?

**Comment by kennethmyhra** [comment]
> Should I implement a pice of code where I get these objects from db and attach them dynamically in runtime?

Yes, that's what you'd have to then.

Thanks for finding that discussion, I was searching through the issues to find it, but couldn't:)
