### ISSUE TITLE
Query the token type through the not modifier.

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/spark#534]
I want to get patient data with `identifier.system` not equal to `http://hl7.org/fhir/sid/us-ssn` and `identifier.code` not equal to `444222222`,Now the server filters all data with `identifier.system`  equal to `http://hl7.org/fhir/sid/us-ssn`.
```
https://spark.incendi.no/fhir/Patient?identifier:not=http://hl7.org/fhir/sid/us-ssn|444222222
```

**Comment by kennethmyhra** [comment]
Hmm, that seems to be unintentional
