### ISSUE TITLE
Searching Patient by Identifier using only System returns InternalServerError

### ISSUE THREAD

**Issue by JeremiahSanders** [FirelyTeam/spark#553]
**Describe the bug**
Searching `Patient` by `Identifier` using only `System` returns `InternalServerError` when properly formatted.

```json
{"resourceType":"OperationOutcome","issue":[{"severity":"error","diagnostics":"FormatException: Token query parameters should at least specify a value after the '|'"}]}
```

I've tested this with both `HTTP GET` and `HTTP POST` search APIs. Both return the same failure, shown above.

This affects attempts to find all patients with `Identifier`s within a given `System`. E.g., searching for all patients within a specific patient domain OID.

**To Reproduce**
1. Send a `Patient` search request to Spark reference server. Include a system, including the 
 trailing `|`, but exclude a value. Example: [`https://spark.incendi.no/fhir/Patient?identifier=urn%3Aoid%3A94461.90476.88752.74168.65258.97141.17793|`](https://spark.incendi.no/fhir/Patient?identifier=urn%3Aoid%3A94461.90476.88752.74168.65258.97141.17793|)

**Expected behavior**
A `Bundle` with matching search results should be returned.
  
**Additional context**

I can confirm that searching by a system _and value_ (`[parameter]=[system]|[code]`) works. Additionally, if the trailing `|` is omitted then it successfully performs a search based upon `value`, matching the `[parameter]=[code]` pattern.

However, following the [ documented `[parameter]=[system]|` pattern](http://hl7.org/fhir/R4/search.html#token), the error shown above occurs.

**Comment by kennethmyhra** [comment]
Thanks for reporting this. Fixed on `r4/master` and `stu3/master`
