### ISSUE TITLE
Bundle response links are broken if ILocalhost.DefaultBase ends with /

### ISSUE THREAD

**Issue by JeremiahSanders** [FirelyTeam/spark#554]
**Describe the bug**
If the Spark configuration specifies a base address with a trailing `/`, notably covering the case of hosting FHIR at the domain root (e.g., `https://localhost:5001/`), all `Bundle` response `Snapshot` links are broken: they are created with doubled `/` characters, resulting in `NotFound` responses when the snapshots are requested.

> NOTE: This is _not_ seen in the Spark reference implementation example site because its base route ends with `fhir`.

**To Reproduce**

1. Initialize a Spark project. Make sure FHIR is hosted at the application root.
2. Provide a configuration where the `SparkSettings.Endpoint` is set to the application's root (e.g., `http://localhost:5000/`). (NOTE: Because `Endpoint` is a `Uri`, even if the `Uri` constructed without a path, e.g., `http://localhost:5000`, the `Uri.ToString()` _will_ have the path `/`, e.g., `http://localhost:5000/`.)
3. Run the server and perform a search or transaction. For most useful result, use a request which will generate _multiple_ response entries and provide a smaller `_count` parameter (so pagination will be needed to retrieve all results).
4. Examine the response `Bundle.Link` contents. You'll see something like the following (however, the host will match whatever you configured):

```json
[{"relation":"self","url":"https://fhir-service:9443//_snapshot?id=c5107296-6dd4-4762-adcc-9809bd5c266d&_offset=0"},{"relation":"first","url":"https://fhir-service:9443//_snapshot?id=c5107296-6dd4-4762-adcc-9809bd5c266d&_offset=0"},{"relation":"last","url":"https://fhir-service:9443//_snapshot?id=c5107296-6dd4-4762-adcc-9809bd5c266d&_offset=3"},{"relation":"next","url":"https://fhir-service:9443//_snapshot?id=c5107296-6dd4-4762-adcc-9809bd5c266d&_offset=1"}]
```

**Expected behavior**
Expectation is that the links will contain no empty segment (i.e., `/`, instead of `//`) between the host and `_snapshot` path.

Example _valid responses_ from Spark reference example server response:

```json
[{"relation":"self","url":"https://spark.incendi.no/fhir/_snapshot?id=c85ca586-4b31-4cc4-88d2-91045d4a365c&_offset=6"},{"relation":"first","url":"https://spark.incendi.no/fhir/_snapshot?id=c85ca586-4b31-4cc4-88d2-91045d4a365c&_offset=0"},{"relation":"last","url":"https://spark.incendi.no/fhir/_snapshot?id=c85ca586-4b31-4cc4-88d2-91045d4a365c&_offset=64"},{"relation":"previous","url":"https://spark.incendi.no/fhir/_snapshot?id=c85ca586-4b31-4cc4-88d2-91045d4a365c&_offset=5"},{"relation":"next","url":"https://spark.incendi.no/fhir/_snapshot?id=c85ca586-4b31-4cc4-88d2-91045d4a365c&_offset=7"}]
```

**Research**

The problem appears to be caused by the manual construction of the snapshot base URL:

https://github.com/FirelyTeam/spark/blob/d9889ad7003c91eabfc6a302416fdf1ef4de8766/src/Spark.Engine/Service/FhirServiceExtensions/SnapshotPaginationService.cs#L209

At that line, the URL is constructed using `baseurl = new Uri(_localhost.DefaultBase + "/" + FhirRestOp.SNAPSHOT).AddParam(FhirParameter.SNAPSHOT_ID, _snapshot.Id);`. As a result, it appends an additional `/` if the `ILocalhost.DefaultBase` _already ends with `/`_.

I imagine that updating the line to `baseurl = _localhost.Absolue(FhirRestOp.SNAPSHOT).AddParam(FhirParameter.SNAPSHOT_ID, _snapshot.Id);` would resolve the issue, given that `Localhost.Absolute` already accounts for trailing `/` (see: https://github.com/FirelyTeam/spark/blob/d9889ad7003c91eabfc6a302416fdf1ef4de8766/src/Spark.Engine/Core/Localhost.cs#L22 ).

**Comment by kennethmyhra** [comment]
Thanks for the thorough report! Fix is on `r4/master` and `stu3/master`, and I'll put up a new release pretty soon.
