### ISSUE TITLE
Present decimal values as integer for Json output

### ISSUE THREAD

**Issue by LeoWirz** [FirelyTeam/spark#563]
**Is your feature request related to a problem? Please describe.**
[It is related to this issue](https://github.com/FirelyTeam/spark/issues/376). The goal was to be able to output round decimal value as integer for "Quantity" (ie. "400.0" should be presented as "400").

The solution of implementing a custom "BsonDecimalSerializer " works to format the decimal value as an integer when we get it from the Mongo DB.

While it works as intended when we get the final output as an XML, we still have an issue when we want to get the result as a JSON because the "FhirJsonSerializer" that is used to produce it adds the ".0" again.

XML output
![image](https://github.com/FirelyTeam/spark/assets/8789213/896bac13-c430-4737-b64e-ee565111330a)
JSON output
![image](https://github.com/FirelyTeam/spark/assets/8789213/bc26db9c-f98a-4b33-a1a2-b439c9f3ebd9)

**Describe the solution you'd like**
A solution would be to add a custom JSON converter for decimal values ([like this)](https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm), but I couldn't find a way of adding a custom converter to the FhirJsonSerializer.

Is there a solution to adapt the FhirJsonSerializer to handle this scenario ?

**Describe alternatives you've considered**
1. Storing integer values as "Integer" instead of "Quantity" but the issue is that the fhir Integer resource does not have some fields such as a "unit".
2. Creating a custom JsonFhirFormatter that doesn't rely on the FhirJsonSerializer

**Comment by kennethmyhra** [comment]
I think this is a question that should be asked in https://github.com/FirelyTeam/firely-net-sdk. `FhirJsonSerializer` is a component that is part of that library.

**Comment by kennethmyhra** [comment]
Closing this. Let me know or re-open if you still think it is relevant.
