### ISSUE TITLE
 Performance degradation in FHIR server for high patient registration volume

### ISSUE THREAD

**Issue by LumiProj** [FirelyTeam/spark#564]
**Describe the bug**
I am experiencing a performance issue with the FHIR server in a hospital environment where approximately 3000 patients register daily. Initially, the server was performing well, with FHIR operations completing in milliseconds. However, after around 2 months of usage, the response time for each operation has increased to 3-4 seconds, causing significant delays in patient care.
 

**Expected behavior**
The FHIR server should maintain consistent response times in the millisecond range, regardless of the number of patients registered.
 

**Spark version**
  - Version: 1.5.17.0

**Operating system + Database**
  - OS: Linux Ubuntu Focal
  - Database:MongoDB

**Comment by kennethmyhra** [comment]
@LumiProj Have you taken a look at the scripts that sets up some database indexes here: https://github.com/FirelyTeam/spark/blob/r4/master/scripts/CreateIndexes.js

The thing with performance degradation in a live environment is that it usually has to be looked on in the context of how that particular instance is used. Those indexes I linked above may or may not solve your problem, if they don't then you would have to research what makes thing slow in your environment. And I would personally have started with monitoring the database.
