### ISSUE TITLE
MongoDb Upgrade 3.x

### ISSUE THREAD

**Issue by Condeti** [FirelyTeam/spark#65]
Hy, 
is a Mongodb 3. x Upgrade planned in future? 
I use the latest version for security reasons. Problematically it becomes fine with the driver there this on the version 3 has changed. I would be glad about this feature :)

**Comment by mharthoorn** [comment]
We have the intention to upgrade, but currently don't have the resources. But we welcome a proper clean pull request.

**Comment by kennethmyhra** [comment]
Spark supports MongoDB 2.x, 3.x, 4.x.
