### ISSUE TITLE
Patient.birthDate has time without a timezone

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/spark#69]
Patient.birthDate is rendered as 2001-11-30T00:00:00 (e.g http://spark.furore.com/fhir/Patient/spark1061) - its type is date and not date-time, so it should not have the time part.

If the time part is specified there should be a time zone specification

**Comment by brianpos** [comment]
Actually think this is a validation issue.
This is what will be on the database and what  sent to the server.
Ewout and I have talked about this one before and not sure what to do when data like this comes in.

**Comment by michelemottini** [comment]
Similar: http://spark.furore.com/fhir/Encounter/spark27 has a date-time without time zone.

Our server at the moment being rejects these date-time (....that is the reason I found the problem ... )
