### ISSUE TITLE
MediaTypeFormatter Task.StartNew choice?

### ISSUE THREAD

**Issue by Keathley3M** [FirelyTeam/spark#71]
I am implementing my own MediaTypeFormatter to handle FHIR requests in an independent web api 2 application.  I looked at the Spark implementations and I noticed the usage of Task.Factory.StartNew.  Was this to satisfy the contract of the async method (ReadFromStreamAsync) or was it chosen for a specific reason?  Just bringing this up in case it may cause issue for the application.

https://github.com/furore-fhir/spark/blob/master/src/Spark.Engine/Formatters/JsonFhirFormatter.cs
Lines 42, 68

> This is particularly true for ASP.NET; there should almost never be a need to call Task.Run (or even worse, StartNew), certainly not in a MediaTypeFormatter class.
> -- Stephen Cleary

Please refer to this article for (not mine) for details:
http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html

**Comment by cknaap** [comment]
Task.Run appears to work just as nice. We'll adjust this for all MediaTypeFormatters.

**Comment by Keathley3M** [comment]
That is specifically called out as a thing not to use.  You risk deadlocks that may not appear when you do a simple debug in Visual Studio.

A better approach (since the request is technically blocked by the media type formatter) would be to use Task.FromResult<object> to satisfy the contract of returning a Task<object>.

**Comment by brianpos** [comment]
That is what we did in sqlonfhir
