### ISSUE TITLE
Unable to find example Database on windows

### ISSUE THREAD

**Issue by larrytamnjong** [FirelyTeam/spark#736]
**Describe the bug**
I cloned the spark-example project but I was unable to find the example the database to restore

![image](https://github.com/FirelyTeam/spark/assets/122117063/cde3593a-036e-4688-b374-80d4cacac90d)

**Comment by kennethmyhra** [comment]
I have just corrected the documentation: https://github.com/FirelyTeam/spark/blob/r4/master/Documentation/Quickstart.md

When standing in the root of this repository run the following command:
```
mongorestore /host:localhost /db:spark-test /archive:.\.docker\linux\r4.archive.gz /gzip
```

**Comment by larrytamnjong** [comment]
Thanks @kennethmyhra When i run the command I get this error 
![image](https://github.com/FirelyTeam/spark/assets/122117063/d43af5ad-4731-490c-81ab-a3a10755f28f)

**Comment by kennethmyhra** [comment]
Seems the `/db` flag is deprecated. Drop that flag and the database will be restored to the same name that it was backed up with which will be `spark`.
