### ISSUE TITLE
Spark.Engine project Naming: Spark.EngineR4 & Spark.EngineSTU3

### ISSUE THREAD

**Issue by johnsierra24** [FirelyTeam/spark#748]
**Problem description**
I can't install the Spark.Engine R4 and Spark.Engine.STU3 packages in the same projects.

**Solution I'd like**
I was wondering if you could change the name of the outputs build dll in, for example, Spark.EngineR4 and Spark.EngineSTU3 in their relative branch.

**Details of my project**
I'm building a project that supports Fhir version HL7.Fhir.STU3 and HL7.Fhir.R4.

Since the original Hl7.Fhir packages have different names between them, I can install Hl7.Fhir.R4.dll and Hl7.Fhir.STU3.dll in the same project.

The project implements through dependency injection some components dedicated to R4 Mode and others to STU3 mode.

I tried to do the same thing with packages Spark.Engine.R4 and Spark.Engine.STU3 but both presents the same dll name and one override the other one.

By downloading the source code of Spark R4/master and Stu3/master and re-building pakages and renaming dll (i chose Spark.EngineR4 and Spark.EngineSTU3 names), I succeded to install Spark.EngineR4 and Spark.EngineSTU in the same projects.

**Additional context**
Spark Versions (nugetpackages)
- Release v2.2.1-stu3 ([link](https://www.nuget.org/packages/Spark.Engine.STU3/2.2.0))
- Release v2.2.1-r4 ([link](https://www.nuget.org/packages/Spark.Engine.R4/2.2.0))

**Comment by kennethmyhra** [comment]
Hey @johnsierra24, that seems reasonable. If it doesn't cause any other problems (which I do not think it will) I will get it into the next release.

**Comment by johnsierra24** [comment]
Thank you very much for your availability! 

Let us know if also you the change is safe

**Comment by kennethmyhra** [comment]
@johnsierra24 this was released just now in 2.3.0
