### ISSUE TITLE
Access by browser does not render OperationOutcome

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/spark#80]
When I do an incorrect get, i.e.

GET /patient

Spark will return a neat OperationOutcome displaying a hint that the casing is wrong.

However, this is only visible when accessing the endpoint using an API or a tool like Fiddler. If you use your browser, the browser will just show an empty page (probably because the HTML renderer that shows nice human output ignores the OperationOutcome?)

**Comment by brianpos** [comment]
This is due to the server so returning an error status code, and the browser press that before the html that is returned.

Do you think it should just display the html content and a system generated 404 style thing?
